// Created 8/30/2013 3:11:48 PM
(function(){var a=function b(){if(2===arguments.length&&"number"===typeof arguments[0]&&"number"===typeof arguments[1])this.x=arguments[0],this.y=arguments[1];else if(1===arguments.length&&arguments[0].type===b.type)this.x=arguments[0].x,this.y=arguments[0].y;else if(0===arguments.length)this.y=this.x=0;else throw"Arguments must be 2 numbers or nothing at all";},e=a.prototype;a.type="Vector2";e.type=a.type;e.set=function(b,c){if(2===arguments.length&&"number"===typeof arguments[0]&&"number"===typeof arguments[1])this.x=
arguments[0],this.y=arguments[1];else if(1===arguments.length&&arguments[0].type===a.type)this.x=arguments[0].x,this.y=arguments[0].y;else throw'Argument must be 2 numbers or 1 "Vector2"';};e.neg=function(){return new a(-this.x,-this.y)};e.vclone=function(){return new a(this.x,this.y)};e.add=function(b){var c=new a(this.x,this.y);if("number"===typeof b)c.x+=b,c.y+=b;else if(b.type&&b.type===a.type)c.x+=b.x,c.y+=b.y;else throw'Argument must be of type "Vector2" or "number"';return c};e.sub=function(b){var c=
new a(this.x,this.y);if("number"===typeof b)c.x-=b,c.y-=b;else if(b.type&&b.type===a.type)c.x-=b.x,c.y-=b.y;else throw'Argument must be of type "Vector2" or "number"';return c};e.mul=function(b){var c=new a(this.x,this.y);if("number"===typeof b)c.x*=b,c.y*=b;else if(b.type&&b.type===a.type)c.x*=b.x,c.y*=b.y;else throw'Argument must be of type "Vector2" or "number"';return c};e.div=function(b){var c=new a(this.x,this.y);if("number"===typeof b)c.x/=b,c.y/=b;else if(b.type&&b.type===a.type)c.x/=b.x,
c.y/=b.y;else throw'Argument must be of type "Vector2" or "number"';return c};e.dot=function(b){if(!b||!b.type||b.type!==a.type)throw'Arguments must be of type "Vector2"';return this.x*b.x+this.y*b.y};e.square=function(){return new a(this.x*this.x,this.y*this.y)};e.vlength=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};e.abs=function(){return new a(Math.abs(this.x),Math.abs(this.y))};e.map=function(b){var c=new a;c.x=b(this.x);c.y=b(this.y);return c};a.dot=function(b,c){if(b.type!==a.type||
c.type!==a.type)throw'Arguments must be of type "Vector2"';return b.x*c.x+b.y*c.y};a.crossVV=function(b,c){if(b.type!==a.type||c.type!==a.type)throw'Arguments must be of type "Vector2"';return b.x*c.y-b.y*c.x};a.crossVN=function(b,c){if(b.type!==a.type||"number"!==typeof c)throw'Arguments must be of type "Vector2" and "number"';return new a(c*b.y,-c*b.x)};a.crossNV=function(b,c){if("number"!==typeof b||c.type!==a.type)throw'Arguments must be of type "number" and "Vector2"';return new a(-b*c.y,b*c.x)};
e.clip=function(b,c,e,j){var f=new a;f.x=Math.max(b,Math.min(e,this.x));f.y=Math.max(c,Math.min(j,this.y));return f};e.toString=function(){return"("+this.x+","+this.y+")"};window.Vector2=a;e.applyAsPosition=function(a){a.style.left=this.x+"px";a.style.top=this.y+"px"};e.applyAsSize=function(a){a.style.width=this.x+"px";a.style.height=this.y+"px"};e.stretchToMe=function(b,c){var e=new a;e.x=Math[c?"min":"max"](this.x,b*this.y);e.y=e.x/b;return e};e.getCenterPosition=function(a){return this.sub(a).div(2)}})();
var _slow=1;function initSimpleUtils(){var a=navigator.userAgent.toLowerCase();ANDROID40=window.system.platform.android&&-1!=a.indexOf("4.0.");ANDROID3=3==window.system.device.version&&window.system.platform.android;ANDROID2=2==window.system.device.version&&window.system.platform.android;FORCE_FLAT=ANDROID3;DEV_3D=Modernizr.csstransforms3d;DOUBLE_CLICK_TO_ZOOM=!0;UP_SCALE=1}
var DEBUG_SHOW_FOLD_SHADOW=!1,TUNE_FOLD_SCALE_ENABLE=!0,TUNE_MINIMUM_FOLD_SCALE=0.25,TUNE_FOLD_SHADOW_ALPHA=!0,TUNE_FOLD_SHADOW_KOEFF=0.35,TIMEOUT_TO_DO_PRETRANSFORM=60*_slow,TIMEOUT_TO_SET_TRANSITION=60*_slow,TIMEOUT_TO_DO_POSTTRANSFORM=60*_slow,TIMEOUT_AFTER_ALL=60*_slow,TUNE_ZINDEX_SINGLE_CANVAS=-100,Z_INDEX_ADD=350,LAST_Z=-300,Z_STEP=5,FIRST_Z=-100,_debugNC=!1,getBookLength=function(){return publicationData.pageCount};
function SoftPlainFlipElements(a,e,d,b,c,u,j){function f(b,h){E+=1;var d=function(){this.style.webkitTransitionProperty="";this.style.webkitTransitionDuration="";this.removeEventListener("webkitTransitionEnd",d,!1);var b=this;setTimeout(function(){h&&h(b);_debugNC&&console.log(a+times()+"timeout",E,b.id);(E-=1)||setTimeout(function(){j&&j(t);G=!1},TIMEOUT_AFTER_ALL)},TIMEOUT_TO_DO_POSTTRANSFORM)};b.addEventListener("webkitTransitionEnd",d,!1)}function A(){startTime=(new Date).getTime();_debugNC&&
console.log(a+times()+"applyDestinationListen",E);f(o,function(){c&&c(t)});k(o,r.flipDiv);f(i);k(i,r.contentObject,s+2);n.backgroundDiv!=r.backgroundDiv&&(f(h),k(h,r.backgroundDiv,s+4));if(l)f(l,function(){}),k(l,r.nextShadow),l.style.opacity="0";g&&w&&(v(g,"end"),f(g,function(){v(g,"start")}))}function v(a,b){var h="start"==b,c=h?TUNE_MINIMUM_FOLD_SCALE:1,e=u?0:d-B,l=dev_translate((h?B*c:0)*(u?-1:1),0,8),c=TUNE_FOLD_SCALE_ENABLE?dev_scale(c<TUNE_MINIMUM_FOLD_SCALE?TUNE_MINIMUM_FOLD_SCALE:c):"";if(TUNE_FOLD_SHADOW_ALPHA)a.style.opacity=
h?"0":"1";a.style.left=e+"px";a.style.webkitTransformOrigin=""+(u?0:B)+"px 0px";a.style.webkitTransform=c+" "+l}function k(a,b,h){var c=void 0==h?a.zOffset||0:h;if(void 0!=h)a.zOffset=h;a.xOffset=b;translate(a,b,c)}function C(a,b){a.zOffset=b;translate(a,a.xOffset||0,b)}function m(){var a={};u?w?(a.flipDiv=0,a.contentObject=0,a.backgroundDiv=-d,a.nextShadow=-p):(a.flipDiv=0,a.contentObject=d,a.backgroundDiv=-d,a.nextShadow=-d):w&&D?(a.flipDiv=0,a.contentObject=0,a.backgroundDiv=d,a.nextShadow=d):
D?(a.flipDiv=0,a.contentObject=-d,a.backgroundDiv=d,a.nextShadow=d):(a.flipDiv=-d,a.contentObject=0,a.backgroundDiv=-d,a.nextShadow=-2*d);return a}this.id=a;var t=this,w=!0,D=!0,p=0.6*d,n=m(),r,I,G,E=0,s=LAST_Z--,B=d*TUNE_FOLD_SHADOW_KOEFF,o=createDiv("flipd"+a,!0);o.style.webkitTransformStyle=ANDROID3||FORCE_FLAT?"flat":"preserve-3d";e.appendChild(o);sizeDiv(o,d,b);C(o,s);var i=createDiv("div"+a);sizeDiv(i,d,b);var F=createCanvas("cc"+a,d,b);i.appendChild(F);i.contentCanvas=F;F=createDiv("vd"+a,
d,b);i.appendChild(F);i.vectorDiv=F;F=createCanvas("tc"+a,d,b);i.appendChild(F);i.topCanvas=F;o.appendChild(i);k(i,n.contentObject,s+2);var h=createBackgroundDiv("backd"+a);sizeDiv(h,d,b);o.appendChild(h);k(h,n.backgroundDiv,s+4);var l=createShadowOnNextDiv("nextsh"+a,u);l&&(e.appendChild(l),sizeDiv(l,p,b),k(l,n.nextShadow,s));var g=createFoldShadow("foldsh"+a,B,b,u);g&&(o.appendChild(g),v(g,"start"));this.flipDiv=o;this.backgroundDiv=h;var z=function(b,h,c){_debugNC&&console.log(a+"prepare",b.id,
E);b.style.webkitTransitionProperty="-webkit-transform "+(c||"");b.style.webkitTransitionTimingFunction="cubic-bezier(0.9,0.05,0.95,1)";b.style.webkitTransitionDuration=""+h*_slow+"s"};this.id=a;var L=function(){n=m();var a={};if(u)if(w&&D)a.flipDiv=d,a.contentObject=-d,a.backgroundDiv=0,a.nextShadow=d-p;else{if(D)a.flipDiv=0,a.contentObject=0,a.backgroundDiv=-d,a.nextShadow=-d}else w&&D?(a.flipDiv=-d,a.contentObject=d,a.backgroundDiv=0,a.nextShadow=0):D?(a.flipDiv=0,a.contentObject=0,a.backgroundDiv=
d+1,a.nextShadow=d):(a.flipDiv=0,a.contentObject=-d,a.backgroundDiv=0,a.nextShadow=-d);r=a;k(o,n.flipDiv,s);k(i,n.contentObject,s+2);k(h,n.backgroundDiv,s+4);g&&v(g,"start");if(l)k(l,n.nextShadow,s),l.style.opacity="1"},J=function(a){z(o,a);z(i,a);z(h,a);l&&z(l,a,"opacity");g&&w&&z(g,a,TUNE_FOLD_SHADOW_ALPHA?"opacity":"")};this.startAnimation=function(a,b,h,c){G=!0;I=c;w=b;D=h;L();setTimeout(function(){J(a);setTimeout(function(){A()},TIMEOUT_TO_SET_TRANSITION)},TIMEOUT_TO_DO_PRETRANSFORM)};this.reset=
function(){w=!0;L()};this.getContentObject=function(){return i};this.getFlipDiv=function(){return o};this.getNextFlipper=function(){return I};this.getFadeout=function(){return w};this.getDepth=function(){return s};this.getBGDiv=function(){return h};this.setNextFlipper=function(a){I=a};this.setDepth=function(a,b){s=a;o.style.zIndex=Z_INDEX_ADD+a;i.style.zIndex=Z_INDEX_ADD+a+1;h.style.zIndex=Z_INDEX_ADD+a+3;if(l)l.style.zIndex=Z_INDEX_ADD+a;if(g)g.style.zIndex=Z_INDEX_ADD+a+4;!0!=b&&(C(o,s),C(i,s+2),
C(h,s+4),l&&k(l,n.nextShadow,s))};this.isFree=function(){return!G};this.clearContent=function(){i.contentCanvas.width=d;i.topCanvas.width=0;deleteAllChildren(i.vectorDiv)};var q;this.setBackgroundContent=function(a){q=a;deleteAllChildren(h);h.appendChild(q)};this.getBGCanvas=function(){q||(q=createFECanvas(a+"bgCont",d,b),h.appendChild(q));return q}}function createFECanvas(a,e,d){a=createCanvas(a);if(a.width!=e||a.height!=d)a.width=e,a.height=d;return a}
var createBackgroundDiv=function(a){a=createDiv(a);a.style.backgroundColor="#dddddf";return a},createShadowOnNextDiv=function(a,e){var d=createDiv(a);d.style.backgroundImage="-webkit-gradient(linear,"+(e?"right bottom,left bottom":"left bottom,right bottom")+", color-stop(1.00, rgba(0,0,0,0)),color-stop(0.00, rgba(0,0,0,0.6)) )";return d},createFoldShadow=function(a,e,d,b){a=createCanvas(a);a.width=e;a.height=d;var c=a.getContext("2d"),b=b?c.createLinearGradient(e,0,0,0):c.createLinearGradient(0,
0,e,0);b.addColorStop(0,"rgba(0, 0, 0, 0)");b.addColorStop(0.72,"rgba(0, 0, 0, 0.2)");b.addColorStop(0.89,"rgba(0, 0, 0, 0.4)");b.addColorStop(1,"rgba(0, 0, 0, 0)");DEBUG_SHOW_FOLD_SHADOW?(c.lineWidth=16,c.strokeStyle="red",c.strokeRect(16,16,e-32,d-32)):(c.fillStyle=b,c.fillRect(0,0,e,d));return a},times=function(){return" "+((new Date).getTime()-startTime)+" "},sizeDim="px";
function sizeDiv(a,e,d,b){if(void 0==e&&void 0==d)e=window.innerWidth,d=window.innerHeight;a.style.width=b?e+"%":Math.ceil(e)+sizeDim;a.style.height=b?d+"%":Math.ceil(d)+sizeDim}function createDiv(a,e){var d=document.createElement("div");d.setAttribute("id",a);d.style.position="absolute";if(e)d.style.overflow="hidden";return d}function createCanvas(a,e,d){var b=document.createElement("canvas");b.setAttribute("id",a);b.style.position="absolute";void 0!=e&&void 0!=d&&sizeCanvas(b,e,d);return b}
function sizeCanvas(a,e,d){a.width=e;a.height=d}function setElementPosition(a,e){a.style.left=(""+e.left).concat("px");a.style.top=(""+e.top).concat("px")}function translate(a,e,d){a.style.webkitTransform="translate3d("+e+sizeDim+",0px,"+(""+d)+sizeDim+")"}function dev_scale(a,e,d){return prepare_xyz("scale",a,e,d)}function dev_translate(a,e,d){return prepare_xyz("translate",a,e,d)}function dev_translate_percents(a,e,d){return prepare_xyz("translate",a,e,d,"%")}
function dev_rotateXY(a){return"rotate"+(DEV_3D?"":"")+"("+a.toString()+"rad)"}function prepare_xyz(a,e,d,b,c){var u="scale"==a,j=u?1:0,c=u?"":c||sizeDim;void 0==e&&(e=j);void 0==d&&(d=j);void 0==b&&(b=j);return a+(DEV_3D?"3d("+e+c+","+d+c+","+b+c+")":"("+e+c+","+d+c+")")}var startTime;function centerRect(a,e,d,b){return{x:(a-d)/2,y:(e-b)/2}}function traceChildren(a){for(var e="",d=0;d<a.length;d++)e+=a[d].id+" ";console.log(e)}
function deleteAllChildren(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
function parseVectorizedContentToDiv(a,e,d,b){for(var b="undefined"!=typeof b?b:!0,c=0;4>c;c++);for(var e=e||createDiv(),c=[],u=0;u<a.length;u++){var j=a[u],f=0,A=j[f++].toString(),v=j[f++].toString(),k=parseFloat(j[f++]);parseFloat(j[f++]);var C=parseFloat(j[f++]),m=parseFloat(j[f++]),t=parseFloat(j[f++]),w=j[f++].toString(),j=parseFloat(j[f++]),D=Math.round(m*d),f=m=document.createElement("p");f.style.position="absolute";f.style.whiteSpace="nowrap";m.innerText=A;m.style.fontFamily=v;f.style.top=
px(Math.round(C*d));f.style.left=px(D);v=t;C=c[v];t="undefined"==typeof C?Math.floor(t*d):C.size;m.style.fontSize=px(t);m.style.color=w;e.appendChild(f);k*=d;if(b)for(;m.offsetWidth>k&&1<t;)t-=1,m.style.fontSize=px(t);if("undefined"==typeof C)c[v]={size:t,elements:[m]};else if(C.size>=t){if(C.size>t){c[v].size=t;for(var p in C.elements)w=C.elements[p],t=w.offsetWidth,w.style.fontSize=px(c[v].size),w.style.wordSpacing="0px",w.style.wordSpacing=px((t-w.offsetWidth)/(w.innerText.split(" ").length-1))}c[v].elements.push(m)}m.style.webkitTransform=
j?dev_rotateXY(j):"";m.style.webkitTransformOrigin=j?"0 0":"";A=A.split(" ");m.style.wordSpacing="0px";m.style.wordSpacing=px((k-m.offsetWidth)/(A.length-1))}return e}function px(a){return a.toString()+"px"}
function scaleAndPositionPageContent(a,e,d){var b=UP_SCALE*parseFloat(publicationData.getPageProperty(a,"width")),a=UP_SCALE*parseFloat(publicationData.getPageProperty(a,"height"));sizeDiv(e,b,a);if(void 0!=d)e.style.left=px(d.x),e.style.top=px(d.y),d=d.width/b,e.style.webkitTransform=dev_scale(d,d),e.style.webkitTransformOrigin="0 0"}
function getPageContentRect(a,e,d){var b=parseFloat(publicationData.getPageProperty(a,"proportions")),a={};a.width=Math.min(b*d,e);a.height=a.width/b;e=centerRect(e,d,a.width,a.height);a.x=e.x;a.y=e.y;return a}function applyRectToCanvas(a,e){a.width=e.width;a.height=e.height;a.style.left=px(e.x);a.style.top=px(e.y)}function fillCanvas(a,e,d){var b=a.getContext("2d");b.fillStyle=void 0!=e?e:"red";d?b.fillRect(d.x,d.y,d.width,d.height):b.fillRect(0,0,a.width,a.height)}
function getIsPreloader(){return!0==window.preloaderIsShown}function showPreloader(){if(!window.preloaderIsShown)window.preloaderIsShown=!0,workspace.preloader.add()}var hidePreloaderTimeout=null;function hidePreloader(){if(window.preloaderIsShown)workspace.preloader.del(),window.preloaderIsShown=!1}function flipPage(a){a?pageMediator.right():pageMediator.left()}function getIsPortrait(){return innerHeight>innerWidth}function getIsAlbum(){return publicationData.type==ALBUM}
function ifParamExist(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");return null!=RegExp("[\\?&]"+a).exec(window.location.href)}window.debugSVG=""!=ifParamExist("s");window.debugSVG_IMG=""!=ifParamExist("i");window.debug_forceSaveScale=""!=ifParamExist("fs");var softFlip=!1;
function OnePage(a,e){var d,b,c,u,j,f,A,v,k,C,m;function t(){var b;debugSVG||(F?(f.parentNode&&f.parentNode.removeChild(f),B()):deleteAllChildren(f));if(A)(b=document.getElementById("stubPage"))&&a.contains(b)&&a.removeChild(b),b=o().div(C).x,v&&parseVectorizedContentToDiv(v,f,b),debugSVG?(N.style.width=o().x+"px",N.style.height=o().y+"px",k.visibility="hidden"):(D("link",publicationData.page[x].links,f),D("video",publicationData.page[x].videos,f)),E();else if(p())b=document.getElementById("stubPage")||
createDiv("stubPage"),sizeDiv(b,innerWidth,innerHeight),b.style.backgroundColor=publicationData.getPageProperty(x,"BGColor"),a.contains(b)||a.appendChild(b)}function w(a,b){if(x!=a){if(x&&p(x)&&!p(a))k.style.visibility="visible";x=a;fconsole.update("pos",x);h||showPreloader();if(p()){A=!1;if(!g)k.style.visibility="hidden";m.set(publicationData.getPageProperty(x,"width"),publicationData.getPageProperty(x,"height"));e(!0);t();hidePreloader();b&&b()}else(function(){v=null;C=new Vector2(publicationData.getPageProperty(x,
"width"),publicationData.getPageProperty(x,"height"));deleteAllChildren(f);loadManager.addPageToQueue({skipCurrentLoading:!0,image:k,quality:!0,position:x,onImageLoadComplete:function(){A=R=!0;T=!1;g&&q.createPattern(k,"no-repeat");var a=new Vector2(k.naturalWidth,k.naturalHeight),b=m.x!=a.x||m.y!=a.y;m=a;e(b);if(debugSVG)N=document.createElement("object"),N.setAttribute("type","image/svg+xml"),N.setAttribute("data","content/psout3.svg"),N.style.pointerEvents="none",f.appendChild(N),f.style.backgroundColor=
"white"},onPageLoadError:function(){A=!1},onAllIsComplete:function(a,h){v=h;t();hidePreloader();b&&b()},onJSLoadComplete:function(){}})})()}}function D(b,h,c,d){var e=o().div(C).x;if("undefined"!=typeof h&&h){var l;for(l=0;l<h.length;l++){var g=h[l],y=new Vector2(g.x,g.y),H=new Vector2(g.width,g.height),f=createDiv(b+l);(function(a,b,h,c){a.style.webkitTransformOrigin="0 0";var d=c?Math.sin(c):0,c=c?Math.cos(c):1;a.style.webkitTransform="matrix("+[c,d,-d,c,b.x,b.y].join()+")";sizeDiv(a,h.x,h.y,!1)})(f,
y.mul(e),H.mul(e),g.angle);if("undefined"!=typeof g.zindex)f.style.zIndex=g.zindex;if("highlight"==b)f.style.backgroundColor=d||highlight.getFillStyle(),c.appendChild(f);else if("link"==b)f.style.backgroundColor=publicationData.linkcolor,f.style.opacity="0.23",(y=g.urls)&&0!=y.length?(g=document.createElement("a"),g.href=y[0],g.target="_blank",g.appendChild(f),c.appendChild(g)):void 0!=g.page&&(function(a){setClickEvents(f,"md",!1);f.addEventListener(SINGLE_CLICK,function(){pageMediator.goToPage(parseInt(a))})}(g.page),
c.appendChild(f));else if("video"==b){f.id="video."+g.id;if(g.showImage){var z=video.getVideoImageUrl(g.imageUri);(function(a){changeUrlWhenPubl(z,function(b){a.style.backgroundImage="url('"+b+"')";a.style.backgroundSize="100% 100%"})})(f)}y=new Image;H=g.height*e;H=50<H?50:0.8*H;y.src=video.getPlayImage();f.appendChild(y);y.style.position="absolute";y.style.margin="auto";y.style.left="0";y.style.right="0";y.style.top="0";y.style.bottom="0";y.style.height=px(H);(function(b){setClickEvents(f,"md",
!1);f.addEventListener(SINGLE_CLICK,function(){video.play(b.type,b.id,function(){a.style.visibility="visible"});a.style.visibility="hidden"})})(g);c.appendChild(f)}}}}function p(a){a=void 0!=a?a:x;return publicationData.getPageProperty(a,"stub")}function n(){var a=x+(d?1:-1);b=!1;c=new Image;z&&L.appendChild(c);loadManager.addPageToQueue({skipCurrentLoading:!1,image:c,quality:!0,position:a,onImageLoadComplete:function(){b=!0;if(z){var a=new Vector2(c.naturalWidth,c.naturalHeight),h=o().x,a=(new Vector2(innerWidth,
innerHeight)).stretchToMe(a.x/a.y,!0);c.style.width=a.x+"px";c.style.height=a.y+"px";G(c,d?h:-a.x,0,!1)}}})}function r(){function a(b,c,d){var l=Math.round(c.x),c=Math.round(c.y),y=0<l?0:Math.abs(l/d),g=0<c?0:Math.abs(c/d),y=Math.min(b.width*d,h)/d-y,g=Math.min(b.height*d,e)/d-g;(y||g)&&q.drawImage(b,l,c,b.width*d,b.height*d)}if(A||p()){var h=J.width,e=J.height;if(!T&&!u&&(j||R||O||P||Q)){q.clearRect(0,0,h,e);if(p())q.fillStyle=publicationData.getPageProperty(x,"BGColor"),q.fillRect(0,0,h,e);else{a(k,
M,K);var l=Math.round(M.x),g=Math.round(M.y);G(f,l,g,!1)}j=Q=P=O=R=!1}if(u&&j){var z,i,y,g=u;z=innerWidth;d?(l=0+(z-g),g/=2,i=l+g,y=g):(i=0,y=g/2,l=i+y,g=y,z=0+z-(l+g));q.clearRect(0,0,h,e);a(k,M,K);if(b){z=c;if(debug_forceSaveScale)n=d?i/K:0,r=0,m=y/K,H=e/K;else var H=(new Vector2(h,e)).stretchToMe(z.width/z.height,!1),n=i*z.width/H.x,r=0,m=y*z.width/H.x,H=e*z.width/H.x;q.drawImage(z,n,r,m,H,i,0,y,J.height)}else q.fillStyle="#efefef",q.fillRect(i,0,y,J.height);y=i=0;d?y=g:i=g;i=q.createLinearGradient(l+
i,0,l+y,0);i.addColorStop(0,"rgba(0, 0, 0, 0)");i.addColorStop(0.72,"rgba(0, 0, 0, 0.2)");i.addColorStop(0.89,"rgba(0, 0, 0, 0.4)");i.addColorStop(1,"rgba(0, 0, 0, 0)");q.fillStyle="#dddddf";q.fillRect(l,0,g,J.height);q.fillStyle=i;q.fillRect(l,0,g,J.height);j=!1}}}function I(){var a=o();if(P||R||Q)k.style.width=1!=K?px(a.x):null,k.style.height=1!=K?px(a.y):null,a=m.map(function(a){return Math.floor((a-1)*K-1)}),sizeDiv(L,a.x,a.y),sizeDiv(f,a.x,a.y),R=P=!1;if(O||Q){var a=Math.round(M.x),b=Math.round(M.y);
G(L,a,b,!1);Q=O=!1}}function G(a,b,h,c){c=c?"%":"px";a.style.left=b.toString()+c;a.style.top=h.toString()+c}function E(){search.active&&search.pages[x]?highlight.getHighlights(x,function(a){s();f.appendChild(S);D("highlight",a,S)}):s()}function s(){deleteAllChildren(S);f.contains(S)&&f.removeChild(S)}function B(){f=createDiv("contentDiv");g?a.appendChild(f):(f.style.webkitTransform=null,L.appendChild(f))}function o(a){a=a||K;return m.map(function(b){return Math.floor(b*a)})}var i=window.system.platform.version,
F="safari"==window.system.browser.name&&fbUtils.isArray(i)&&2<=i.length&&"4"==i[0]&&2<=i[1],h="safari"==window.system.browser.name&&fbUtils.isArray(i)&&3==i.length&&"4"==i[0]&&"0"==i[1]&&"4"==i[2],l=ifParamExist("c")?"canvas":"webkit",g="canvas"==l,z="webkit"==l;if(z)var L=createDiv("scrollDiv");f=void 0;A=void 0;v=void 0;k=void 0;C=void 0;m=void 0;new Image;var J=document.createElement("canvas"),q=J.getContext("2d");A=!1;var R,M=new Vector2(0,0),K=0.1,O,P,Q,x;m=new Vector2;C=new Vector2(100,100);
this.goToPage=function(a){w(a,function(){customEvents.fireEvent(ANDROID_PAGE_PREPARED,{page:p()?[]:[x]})})};this.resize=function(){t();g?(J.width=innerWidth,J.height=innerHeight):sizeDiv(a,innerWidth,innerHeight)};this.setOffset=function(a,b){M.set(a);if(!b||!z)O=!0};d=void 0;b=void 0;c=void 0;u=void 0;j=void 0;this.setFlipOffset=function(a,b){!u&&a&&n();u=a;d=b;j=!0};this.setScale=function(a,b){K=a;if(!b||!z)P=!0};this.startPinchMode=function(){f.style.visibility="hidden";if(!debugSVG&&!g)this.pinchRedrawInterval=
setInterval(function(){Q=!0},1E3)};this.stopPinchMode=function(){t();if(this.pinchRedrawInterval)clearInterval(this.pinchRedrawInterval),this.pinchRedrawInterval=null;f.style.visibility="visible";z&&(P=O=!0)};this.updateTopContent=function(){t()};var N,T=!1;this.setFinished=function(){T=!0;z&&a.removeChild(c)};var S=createDiv("highlightContainer");this.setHighlight=function(a){a?E():(search.active=!1,s())};this.set=function(b,h){fconsole.update("mode",l);g?(a.style.overflow="visible",a.appendChild(J)):
(a.style.position="absolute",L.style.webkitTransform=null,a.style.webkitTransform=null,a.style.overflow="hidden",a.appendChild(L));k=new Image;if(!g)k.style.webkitTransform=null,k.style.position="absolute",L.appendChild(k),k.style.border="1px solid #333333";B();w(b,h)};this.getScaledSize=o;this.getImageLoaded=function(){return A};this.isStub=function(){return p()};this.getContentSize=function(){return m};this.drawFrame=g?r:I;this.canFlip=function(a){return a?x<getBookLength():1<x}}
function SimpleViewer(a){function e(){(new Date).getTime();window.requestAnimFrame=window.requestAnimFrame||function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();(function l(){r.drawFrame(F);requestAnimFrame(l)})()}function d(a,b){a!=p&&(p=a,fconsole.update("scale",p),r.setScale(p,b),b||k())}function b(a,b){a.sub(D).vlength()&&(D=
a,r.setOffset(D,b))}function c(a,b){var c=new u(b);return a.clip(c.xmin,c.ymin,c.xmax,c.ymax)}function u(a){var b=r.getScaledSize(a).x,a=r.getScaledSize(a).y;b>innerWidth?(this.xmax=0,this.xmin=innerWidth-b):this.xmax=this.xmin=innerWidth/2-b/2;a>innerHeight?(this.ymax=0,this.ymin=innerHeight-a):this.ymax=this.ymin=innerHeight/2-a/2}function j(a,e,g){var f=p,a=e&&v(n.map,p)>=n.map.length-1?n.defaultPos:v(n.map,p*(e?2:1))+(e?0:a?1:-1),a=Math.min(Math.max(a,0),n.map.length-1),a=n.map[a],g=g?g:t?new Vector2(innerWidth/
2,innerHeight/2):new Vector2(publicationData.rtlMode?innerWidth:0,0),f=D.sub(g.sub(D).mul(a/f-1)),f=c(f,a);d(a);b(f);r.updateTopContent()}function f(a,e){var g,f,i=r.getContentSize();g="change"==a;var k="resize"==a;f=g&&!e&&w;var q=n,m=g&&e||k;if(m){var j=(new Vector2(innerWidth,innerHeight)).stretchToMe(i.x/i.y,!0).x/i.x,q=innerWidth/i.x,i=q/0.8,o;t?(j=[j],o=1.5):(j=[q],o=Math.sqrt(i/q),j=j.concat([q*o,i]));for(;2.15>j[j.length-1]*o;)j[j.length]=j[j.length-1]*o;A(j,0.25,o);A(j,0.5,o);A(j,0.75,o);
A(j,1,o);q={defaultPos:0,map:j,textVisibleMaxPos:4}}fconsole.log(g,e,k,m||t||!window.debug_forceSaveScale&&v(n.map,p)>n.textVisibleMaxPos);k=m||t||!window.debug_forceSaveScale&&v(n.map,p)>n.textVisibleMaxPos?q.map[q.defaultPos]:p;m=r.getScaledSize(k).x;i=r.getScaledSize(k).y;j=D.vclone();if(!f)j.x=t?(innerWidth-m)/2:publicationData.rtlMode?innerWidth-m:0;if(g)j.y=t?(innerHeight-i)/2:0;g=c(j,k);f=q;n=f;b(g);d(k)}function A(a,b,c){for(var d=Math.abs(a[0]-b),e=1,f=0;e<a.length;){var i=Math.abs(a[e]-
b);i<d&&(d=i,f=e);e++}(b+d)/(b-d)<c&&0!=f&&(a[f]=b)}function v(a,b){for(var c=0;c<a.length;c++){var d=a[c];if(0==c){if(b<=d||1==a.length)return 0}else{if(c==a.length-1)return a.length-1;if(b<a[c])return b<=(a[c-1]+a[c])/2?c-1:c;if(b<=(a[c]+a[c+1])/2)return c}}throw"determineScale abnormal return";}function k(){customEvents.fireEvent(ZOOM_LEVEL_CHANGED_FOR_WORKSPACE,{isSmallest:0==v(n.map,p),isLargest:v(n.map,p)==n.map.length-1})}function C(a,d,e){var f,j,k,q,n,p,t,v,s;function u(a){G.active=!1;a.ctrlKey&&
(d.sendPinch&&(d.startPinch&&d.startPinch(new Vector2(a.pageX,a.pageY)),d.sendPinch(U,new Vector2(0,0),new Vector2(a.pageX,a.pageY)),d.endPinch&&d.endPinch()),a.stopImmediatePropagation());a.altKey&&d.sendPinch&&(d.startPinch&&d.startPinch(new Vector2(a.pageX,a.pageY)),d.sendPinch(V,new Vector2(0,0),new Vector2(a.pageX,a.pageY)),d.endPinch&&d.endPinch());a.shiftKey&&d.handleDoubleClick(a);var b=a.currentTarget;if(Modernizr.touch){if(1<a.touches.length){w(a);return}b.addEventListener(DOWN_EVENT,w,
!1)}b.removeEventListener(DOWN_EVENT,u,!1);b.addEventListener(MOVE_EVENT,x,!1);b.addEventListener(UP_EVENT,B,!1);b.addEventListener("touchcancel",B,!1);b.addEventListener("mouseout",B,!1);a=a.touches?a.touches[0]:a;b.pos=new Vector2(a.pageX,a.pageY);F.disabledThisTime=!1;I()}function x(a){a.preventDefault();var d=a.touches?a.touches[0]:a,d=new Vector2(d.pageX,d.pageY),h=a.currentTarget.pos;a.currentTarget.pos=d;a=d.sub(h);f=f||a.x;if(j){d=(new Date).getTime();h=d-j;k=k.add(a);q+=h;j=d;n+=Math.abs(a.x);
p.push({dv:a,time:h});d=r.getScaledSize(void 0).x<=innerWidth||r.isStub();if(e)if(h=k.y?Math.abs(k.x)/Math.abs(k.y):1E10,Math.abs(k.x)>W/1.5*(1.5-h))t=!0;else if(k.y&&!(1.5<h)&&!t)a.x=0;if(1E3<q||f&&a.x&&f/Math.abs(f)!=a.x/Math.abs(a.x))v=!0;if(!v&&k.x&&0.5>Math.abs(k.y)/Math.abs(k.x))a.y=0;if(d&&!v&&4<n&&75<q){for(var l=p,d=r.getScaledSize(void 0).y>innerHeight,m,s,u,w=u=s=h=m=0;w<l.length;w++){var x=l[w];m+=x.dv.x;h+=x.dv.y;s+=Math.abs(x.dv.x);u+=x.time}l=Math.abs(m);s=Math.abs(s-l);m=0>m;14>s&&
7<l&&(!d&&1>=Math.abs(h)/l||d&&l>7+200*Math.abs(h)/l&&l>0.2*u)?(flipPage(m),d=!0):d=!1;d&&(v=!0)}}if(a.x||a.y)b(c(D.add(a))),0!=o&&(i={dv:a,time:(new Date).getTime()-o}),o=(new Date).getTime()}function w(a){if(1<a.touches.length){var b=a.currentTarget,c=a.touches[0],a=a.touches[1];b.pos=new Vector2((c.pageX+a.pageX)/2,(c.pageY+a.pageY)/2);b.startDist=m(c,a);b.removeEventListener(UP_EVENT,B,!1);b.removeEventListener("touchcancel",B,!1);b.removeEventListener(MOVE_EVENT,x,!1);b.removeEventListener(DOWN_EVENT,
w,!1);b.addEventListener(MOVE_EVENT,C,!1);b.addEventListener(UP_EVENT,A,!1);b.addEventListener("touchcancel",A,!1);d.startPinch&&d.startPinch(b.pos)}}function C(a){a.preventDefault();if(1<a.touches.length){var b=a.currentTarget,c=a.touches[0],e=a.touches[1],a=m(c,e),c=new Vector2((c.pageX+e.pageX)/2,(c.pageY+e.pageY)/2),e=a/b.startDist,h=c.sub(b.pos);d.sendPinch(e,h,c);b.startDist=a;b.pos=c}}function A(a){var b=a.currentTarget,c=a.touches.length;if(0<c){b.removeEventListener(MOVE_EVENT,C,!1);b.removeEventListener(UP_EVENT,
A,!1);b.removeEventListener("touchcancel",A,!1);b.addEventListener(MOVE_EVENT,x,!1);b.addEventListener(UP_EVENT,B,!1);b.addEventListener("touchcancel",B,!1);var e=a.touches?a.touches[0]:a;b.pos=new Vector2(e.pageX,e.pageY);I()}d.endPinch&&d.endPinch();0==c&&B(a)}function E(a){s||(s=setTimeout(function(){t=!1;s=null},a))}function B(a){var b=a.currentTarget;if(!Modernizr.touch||!a.touches||0==a.touches.length)b.removeEventListener(MOVE_EVENT,x,!1),b.removeEventListener(UP_EVENT,B,!1),b.removeEventListener("touchcancel",
B,!1),b.removeEventListener("mouseout",B,!1),b.addEventListener(DOWN_EVENT,u,!1);E(X);F.active?F.finishing||F.stop():(i&&100>(new Date).getTime()-o&&(i.dv.x&&r.getScaledSize(void 0).x>innerWidth||i.dv.y&&r.getScaledSize(void 0).y>innerHeight)&&G.startKinematics(i.dv,i.time),i=null,o=0)}function I(){j=(new Date).getTime();q=0;p=[];n=0;v=!1;f=0;k.set(0,0)}var U=1.15,V=0.8,W=innerWidth/4,X=1250;a.addEventListener(DOWN_EVENT,u,!1);f=void 0;j=void 0;k=void 0;q=void 0;n=void 0;p=void 0;t=void 0;v=void 0;
s=void 0;k=new Vector2(0,0)}function m(a,b){var c=a.pageX-b.pageX,d=a.pageY-b.pageY;return Math.sqrt(c*c+d*d)}var t=publicationData.type==PT_PHOTOALBUM,w=publicationData.type==PT_BOOK,D=new Vector2(0,0),p=0.1,n,r=new OnePage(a,function(a){f("change",a)});this.goToPage=function(a){r.goToPage(a)};var I=this;setInterval(function(){(I.width!=innerWidth||I.height!=innerHeight)&&I.resize()},1E3);this.resize=function(){this.width=innerWidth;this.height=innerHeight;r.getImageLoaded()&&f("resize");r.resize()};
var G={startKinematics:function(){},active:!1,iterate:function(a){this.time+=a;this.time=Math.min(this.time,this.duration);a=this.time/this.duration-1;if(this.time==this.duration)this.active=!1;return G.startPoint.add(G.endPoint.sub(G.startPoint).mul(a*a*a+1))}},E,s=function(){var a=document.createElement("p");a.style.opacity="0.7";a.style.backgroundColor="#e0efee";a.style.color="#11111f";a.style.fontSize="18px";a.style.zIndex=1E3;a.style.position="absolute";this.element=a};s.prototype.setText=function(a){this.element.innerText=
a};s.prototype.positionMe=function(a){this.element.style.left=px(a.x-this.element.offsetWidth/2);this.element.style.top=px(a.y-this.element.offsetHeight/2)};var B=new s;this.sendMove=function(){};var o=0,i;this.stopDrag=function(){};this.startPinch=function(b){G.active=!1;a.appendChild(B.element);B.positionMe(b);E?(clearTimeout(E),E=null):r.startPinchMode()};this.endPinch=function(){a.removeChild(B.element);E=setTimeout(function(){r.stopPinchMode();E=null;k()},r.isStub()||debugSVG?0:500)};this.sendPinch=
function(a,e,f){p*a<n.map[0]?a=n.map[0]/p:p*a>n.map[n.map.length-1]&&(a=n.map[n.map.length-1]/p);e=e.add(f.sub(D).mul(1-a));e=D.add(e);a*=p;e=c(e,a);d(a,!0);b(e,!0);B.setText(window.LOCALS.ZOOM+" "+(100*p).toFixed(0)+"%");B.positionMe(f)};this.incZoom=function(){j(!0)};this.decZoom=function(){j(!1)};this.setHighlight=function(a){r.setHighlight(a)};this.set=function(b,c){setElementPosition(a,{left:0,top:0});r.set(b,c);this.resize();e();C(a,this,publicationData.type!=PT_PHOTOALBUM)};this.clear=function(){};
this.handleDoubleClick=function(a){a=a.touches?a.touches[0]:a;a=new Vector2(a.pageX,a.pageY);j(!0,!0,a)};var F={active:!1,handleFlipFinished:function(){r.setFinished();flipPage(this.right)},start:function(a,b){this.drag=0;this.userDrag=a;this.right=b;this.active=!0;this.setChanged()},stop:function(){this.active=this.finishing=!1;this.setChanged()},updateDrag:function(a){this.userDrag=a},setChanged:function(){this.changed=!0;r.setFlipOffset(this.active?this.drag:0,this.right)},iterate:function(){this.finishing?
(this.drag+=(2*innerWidth-this.drag)/2,1>Math.abs(this.drag-2*innerWidth)&&(this.handleFlipFinished(),this.stop())):this.drag+=(this.userDrag-this.drag)/5;this.setChanged()},finish:function(){this.finishing=!0;this.setChanged()}}};
