// Created 8/30/2013 3:11:50 PM
function IOSBook(q,c){this.type=c||orientationObserver.getType();q=q||1;this.onePage=new OnePagePublication(q);this.twoPage=new TwoPagePublication(q);this.zoomBook=new ZoomIOSPublication(1);this.onePage.initSizes();this.twoPage.initSizes();this.touchTrigg=0;1==this.type?this.onePage.drawBook():2==this.type?this.twoPage.drawBook():3==this.type&&(this.zoomBook.initSizes(3.3),this.zoomBook.drawBook());this.goToPage=function(a){1==this.type?this.onePage.goToPage(a):2==this.type?this.twoPage.goToPage(a):
3==this.type&&this.zoomBook.goToPage(a)};var d=this,n=function(a){1==d.type&&d.onePage.goToZoom(a);if(2==d.type){var b=a.target.id.match(/\d+/i);d.twoPage.goToZoom(b)}3==d.type&&(2===orientationObserver.getType()?d.zoomBook.goToTwoPage(a):d.zoomBook.goToOnePage(a))};el.id("mainFrame").addEventListener("dblclick",n);el.id("mainFrame").addEventListener("touchend",function(){0===d.touchTrigg?(d.touchTrigg++,setTimeout(function(){d.touchTrigg=0},250)):!d.twoPage.gesture&&!d.onePage.gesture&&!d.zoomBook.gesture&&
n(event)});customEvents.addListener(ROTATE_DEVICE,function(a){if(2===a.data&&1===d.type)d.type=2,d.onePage.destroyBook(),setTimeout(function(){d.twoPage.initSizes();var a=pageTable.getUserIDFromFileID(pageMediator.page);d.twoPage.drawBook(a)},10);else if(1===a.data&&1===d.type)d.type=1,d.onePage.destroyBook(),setTimeout(function(){d.onePage.initSizes();d.onePage.drawBook(pageMediator.page)},10);else if(1===a.data&&2===d.type)d.type=1,d.twoPage.destroyBook(),setTimeout(function(){d.onePage.initSizes();
d.onePage.drawBook(pageMediator.page)},10);else if(2===a.data&&2===d.type)d.type=2,d.twoPage.destroyBook(),setTimeout(function(){d.twoPage.initSizes();d.twoPage.drawBook(pageMediator.page)},10)});customEvents.addListener(ZOOM_ANIMATION_START,function(){});customEvents.addListener(ZOOM_ANIMATION_END,function(a){d.type=3;customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:3});d.zoomBook.initSizes(a.data.zoomFactor,a.data.page);d.zoomBook.drawBook(a.data.page);if(GAEnable){var b=window.location.pathname.split("/");
_trackEvent(b[b.length-4]+"","Zooming","page"+a.data.page)}});customEvents.addListener(ZOOM_ANIMATION_END_TO_ONE,function(a){d.type=1;customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:1});d.onePage.initSizes();d.onePage.drawBook(a.data.page);if(GAEnable){var b=window.location.pathname.split("/");_trackEvent(b[b.length-4]+"","Zooming out","page"+a.data.page)}});customEvents.addListener(ZOOM_ANIMATION_END_TO_TWO,function(a){customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:2});d.type=2;d.twoPage.initSizes();
d.twoPage.drawBook(a.data.page);if(GAEnable){var b=window.location.pathname.split("/");_trackEvent(b[b.length-4]+"","Zooming out","page"+a.data.page)}});customEvents.addListener(ZOOM_ZOOM_ANIMATION_END,function(a){customEvents.fireEvent(CHANGE_BOOK_TYPE,{type:3});d.type=3;d.zoomBook.initSizes(a.data.zoomFactor,a.data.page);d.zoomBook.drawBook(a.data.page,a.data.startPos)});el.id("mainFrame").addEventListener("gesturestart",function(){ZOOM_LOCK||(1===d.type?d.onePage.gesturestart(event):2===d.type?
d.twoPage.gesture||d.twoPage.gesturestart(event):3===d.type&&d.zoomBook.gesturestart(event))},!0);el.id("mainFrame").addEventListener("gesturechange",function(){ZOOM_LOCK||(1===d.type?d.onePage.gesturechange(event):2===d.type?d.twoPage.gesturechange(event):3===d.type&&d.zoomBook.gesturechange(event))},!0);el.id("mainFrame").addEventListener("gestureend",function(){ZOOM_LOCK||(1===d.type?d.onePage.gestureend(event):2===d.type?d.twoPage.gestureend(event):3===d.type&&d.zoomBook.gestureend(event))},!0);
customEvents.addListener(START_ZOOM_PRELOADER,function(a){ZOOM_LOCK=!0;var a=void 0!=a.data?a.data.shift:0,b=el.add("div");b.id="preloaderZOOM";b.style.position="absolute";b.style.left=window.innerWidth/2+a+"px";b.style.top=window.innerHeight/2+"px";b.style.width="10em";b.style.height="10em";b.style.margin="-3em 0 0 -5em";b.style.zIndex=1E7;b.style.webkitTransform="translateZ(150px)";workspace.preloader.add(b);el.id("mainFrame").appendChild(b);page=null});customEvents.addListener(STOP_ZOOM_PRELOADER,
function(){el.del("preloaderZOOM");setTimeout(function(){ZOOM_LOCK=!1},300)});var a=function(){1===d.type?d.onePage.touch(event):2===d.type?d.twoPage.touch(event):3===d.type&&d.zoomBook.touch(event);system.device.iphone&&window.scrollTo(0,1)},b=function(){1===d.type?d.onePage.endmove(event):2===d.type?d.twoPage.endmove(event):3===d.type&&d.zoomBook.endmove(event)};Modernizr.touch?(el.id("mainFrame").addEventListener("touchstart",a,!0),el.id("mainFrame").addEventListener("touchend",b,!0)):(el.id("mainFrame").addEventListener("mousedown",
a,!0),el.id("mainFrame").addEventListener("mouseup",b,!0))}iosContent={};
function OnePagePublication(q){this.HORIZONTAL_MARGIN=this.VERTICAL_MARGIN=10;this.bookLeft=this.bookTop=this.bookHeight=this.bookWidth=this.pageHeight=this.pageWidth=0;this.active=this.block=!1;this.currentPage=q||1;this.pageBuff=1;this.flipSpeed=500;this.gesture=!1;this.loadBuffers={};this.initSizes=function(){var a=publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>a?(this.bookHeight=window.innerHeight-2*this.VERTICAL_MARGIN,this.bookWidth=this.bookHeight*
a,this.bookLeft=(window.innerWidth-this.bookWidth)/2,this.bookTop=this.VERTICAL_MARGIN):(this.bookWidth=window.innerWidth-2*this.HORIZONTAL_MARGIN,this.bookHeight=this.bookWidth/a,this.bookLeft=this.HORIZONTAL_MARGIN,this.bookTop=(window.innerHeight-this.bookHeight)/2);this.pageHeight=this.bookHeight;this.pageWidth=this.bookWidth;this.translateX=2*this.bookLeft+this.pageWidth};this.init=function(){var a=this;customEvents.addListener(SHOW_SEARCH_RESULTS,function(){if(a.active){highlight.show(a.currentPage);
for(var b=a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.show(b)}});customEvents.addListener(CANCEL_SEARCH,function(){if(a.active){highlight.hide(a.currentPage);for(var b=a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.hide(b)}});customEvents.addListener(BOOK_FLIPPING_START,function(){a.block=!0});customEvents.addListener(BOOK_FLIPPING_END,function(){a.block=!1});customEvents.addListener(IOS_LOAD_PAGE_START,function(a){var e=
a.data.page;if(1===a.data.type&&!publicationData.page[e].stub)a=el.add("div"),a.id="preloader"+e,a.style.position="absolute",a.style.left="50%",a.style.top="50%",a.style.width="10em",a.style.height="10em",a.style.margin="-3em 0 0 -5em",workspace.preloader.add(a),publicationData.page[e].wide?el.id("widePage"+e).appendChild(a):el.id("divPage"+e).appendChild(a)});customEvents.addListener(IOS_LOAD_BITMAP_END,function(a){var e=a.data.page;1===a.data.type&&!publicationData.page[e].stub&&el.del("preloader"+
e)});customEvents.addListener(IOS_LOAD_VECTOR_END,function(){})};this.drawBook=function(a){this.active=!0;a=a||-10;if(-10!=a)this.currentPage=a;this.init();a=el.add("div");a.id="publicationDiv";a.style.width=this.bookWidth+"px";a.style.height=this.bookHeight+"px";a.style.top=this.bookTop+"px";a.style.left=this.bookLeft+"px";a.style.position="absolute";a.style.textAlign="center";a.style.opacity="1";el.id("mainFrame").appendChild(a);this.drawPage(this.currentPage);for(a=this.currentPage-this.pageBuff;a<=
1*this.currentPage+this.pageBuff;a++)a!==this.currentPage&&this.drawPage(a)};this.drawPage=function(a){if(publicationData.page[a]&&!el.id("divPage"+a)){var b=publicationData.page[a].wide;if(b){var e=el.add("div");e.id="divPage"+a;e.className="oneBook";e.style.width=this.pageWidth+"px";e.style.height=this.pageHeight+"px";e.style.position="absolute";e.style.backgroundColor="rgba(0,0,0,0)";e.style.color="black";e.style.left=publicationData.rtlMode?a>this.currentPage?-window.innerWidth+"px":a<this.currentPage?
window.innerWidth+"px":"":a<this.currentPage?-window.innerWidth+"px":a>this.currentPage?window.innerWidth+"px":"";var c=publicationData.rtlMode?publicationData.pageCount+a:publicationData.pageCount-a;e.style.zIndex=c+"";c=null;el.id("publicationDiv").appendChild(e)}var g=el.add("div");g.id=b?"widePage"+a:"divPage"+a;g.className="oneBook";g.style.width=this.pageWidth+"px";g.style.height=b?this.pageHeight/2+"px":this.pageHeight+"px";g.style.position="absolute";"photo_album"==publicationData.type||"document"==
publicationData.type?g.style.backgroundColor="rgba(0,0,0,0)":(g.style.backgroundColor=publicationData.page[a].BGColor||publicationData.page.defaults.BGColor,HTML5lib.boxShadow(g,"0px 0px 3px #000"));g.style.color="black";if(b)g.style.top=this.pageHeight/4+"px";if(publicationData.rtlMode)if(!b&&a>this.currentPage)g.style.left=-window.innerWidth+"px";else if(!b&&a<this.currentPage)g.style.left=window.innerWidth+"px";else{if(!b)g.style.left=""}else if(!b&&a<this.currentPage)g.style.left=-window.innerWidth+
"px";else if(!b&&a>this.currentPage)g.style.left=window.innerWidth+"px";else if(!b)g.style.left="";c=publicationData.rtlMode?publicationData.pageCount+a:publicationData.pageCount-a;g.style.zIndex=c+"";c=null;c=this.injectCanvas(g,a);b?e.appendChild(g):el.id("publicationDiv").appendChild(g);publicationData.page[a].stub?(customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:a,type:1}),customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:a,type:1}),ZOOM_LOCK&&el.id("exPage"+a)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),
setTimeout(function(){el.del("exPage"+a)},50))):(customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:a,type:1}),this.loadImage(c,a))}};this.injectCanvas=function(a,b){var e=publicationData.page[b].wide?this.pageHeight/2:this.pageHeight,c=publicationData.page[b].width||publicationData.page.defaults.width,g=publicationData.page[b].height||publicationData.page.defaults.height,j=c/g;if(this.pageWidth/e>j)var f=e,d=f*j,j=(this.pageWidth-d)/2,e=0;else d=this.pageWidth,f=d/j,j=0,e=(e-f)/2;var l=el.add("canvas");
l.id="substraitCanvas"+b;l.width=d;l.height=f;l.style.position="absolute";l.style.left=j+"px";l.style.top=e+"px";a.appendChild(l);var h=d/(2*c);("photo_album"==publicationData.type||"document"==publicationData.type)&&HTML5lib.boxShadow(l,"0px 0px 3px #000");var m=publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===m||"js+png"===m)m=el.add("div"),m.id="contentDiv"+b,m.style.width=2*c+"px",m.style.height=2*g+"px",m.style.position="absolute",m.style.left=j+"px",m.style.top=
e+"px",m.style.webkitTransformOrigin="0% 0%",m.style.webkitTransform="scale("+h+")",a.appendChild(m);var o=el.add("canvas");o.id="highlightCanvas"+b;o.width=d;o.height=f;o.style.position="absolute";o.style.left=j+"px";o.style.top=e+"px";o.style.opacity=0;a.appendChild(o);new LinksLayer(o,b);highlight.show(b,o);var p=function(){o.style.opacity=1;customEvents.removeListener(IOS_LOAD_BITMAP_END,p)};customEvents.addListener(IOS_LOAD_BITMAP_END,p);return l};this.destroyPage=function(a){el.id("divPage"+
a)&&el.del("divPage"+a)};this.destroyBook=function(){el.del("publicationDiv");this.active=!1};this.goToPage=function(a){var b=this;if(a==this.currentPage+1)a=this.currentPage-this.pageBuff,b.destroyPage(a),publicationData.rtlMode?this.shiftRight():this.shiftLeft(),this.currentPage++,this.drawPage(this.currentPage+this.pageBuff);else if(a==this.currentPage-1)a=this.currentPage+this.pageBuff,b.destroyPage(a),publicationData.rtlMode?this.shiftLeft():this.shiftRight(),this.currentPage--,this.drawPage(this.currentPage-
this.pageBuff);else if(a!=this.currentPage){if(1*a>1*this.currentPage){var e=1*this.currentPage+1;this.clearContent(e);publicationData.rtlMode?this.shiftRight():this.shiftLeft()}else e=this.currentPage-1,this.clearContent(e),publicationData.rtlMode?this.shiftLeft():this.shiftRight();this.currentPage=a;var c=function(){b.destroyBook();b.drawBook(b.currentPage);delete c};window.setTimeout(c,b.flipSpeed);pageMediator.changePage(a)}};this.clearContent=function(a){if(el.id("divPage"+a))el.id("divPage"+
a).style.backgroundColor="white",el.id("substraitCanvas"+a)&&el.del("substraitCanvas"+a),el.id("videoDiv"+a)&&el.del("videoDiv"+a),el.id("contentDiv"+a)&&el.del("contentDiv"+a),el.id("highlightCanvas"+a)&&el.del("highlightCanvas"+a)};this.shiftLeft=function(){for(var a=this.currentPage-this.pageBuff;a<=this.currentPage+this.pageBuff;a++)if(el.id("divPage"+a)){var b=el.id("divPage"+a);HTML5lib.duration(b,this.flipSpeed);0==1*HTML5lib.getParseTranslate(b).x?(customEvents.fireEvent(BOOK_FLIPPING_START),
HTML5lib.translate(b,-this.translateX,0,0)):1*HTML5lib.getParseTranslate(b).x==-this.translateX?HTML5lib.translate(b,2*-this.translateX,0,0):1*HTML5lib.getParseTranslate(b).x==2*this.translateX?(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,this.translateX,0,0)):(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,0,0,0))}var e=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:e.currentPage})},this.flipSpeed)};this.shiftRight=function(){for(var a=
this.currentPage-this.pageBuff;a<=this.currentPage+this.pageBuff;a++)if(el.id("divPage"+a)){var b=el.id("divPage"+a);HTML5lib.duration(b,this.flipSpeed);0==1*HTML5lib.getParseTranslate(b).x?(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,this.translateX,0,0)):1*HTML5lib.getParseTranslate(b).x==this.translateX?(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,2*this.translateX,0,0)):1*HTML5lib.getParseTranslate(b).x==2*-this.translateX?(customEvents.fireEvent(BOOK_FLIPPING_START),
HTML5lib.translate(b,-this.translateX,0,0)):(customEvents.fireEvent(BOOK_FLIPPING_START),HTML5lib.translate(b,0,0,0))}var e=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:e.currentPage})},this.flipSpeed)};this.loadImage=function(a,b){var e=a.getContext("2d");e.fillStyle="rgb(255,255,255)";var c=publicationData.page[b].proportions||publicationData.page.defaults.proportions,g=publicationData.size.proportions,d=a.width,f=a.height,k=new Image,l=publicationData.page[b].format||
publicationData.page.defaults.format,h=publicationData.page[b].zoomFormat||publicationData.page.defaults.zoomFormat||publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===l){var m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".jpg";this.loadContent(b,d)}else"js+png"===l?(m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".png",this.loadContent(b,d)):"jpg"===h?m=ASSETS_FOLDER+"/pages/page"+this.getName(b)+"_i2.jpg":"png"===h&&(m=ASSETS_FOLDER+"/pages/page"+
this.getName(b)+"_i2.png");changeUrlWhenPubl(m,function(a){k.src=a});if(c>=g)var o=d,p=(o/c+0.5).toFixed(0),n=0,q=(f-p)/2;else p=f,o=(p*c+0.5).toFixed(0),n=(d-o)/2,q=0;k.onload=function(){ZOOM_LOCK&&el.id("exPage"+b)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+b)},50));e.drawImage(k,n,q,o,p);customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:b,type:1})}};this.addContentDiv=function(){};this.loadContent=function(a){var a=ASSETS_FOLDER+"/pages/ios/page"+this.getName(a)+
".js",b=document.getElementsByTagName("head")[0],e=document.createElement("script");e.id="formPrinter";e.type="text/javascript";changeUrlWhenPubl(a,function(a){e.src=a});b.appendChild(e);window.fakeLoadComplete=function(a){window.loadBuffers[a]=window.loadBuffer;for(i in window.loadBuffers[a]){var b=el.add("p");b.style.position="absolute";b.style.fontFamily=window.loadBuffers[a][i][1];b.style.width=2*window.loadBuffers[a][i][2]+"px";b.style.height=2*window.loadBuffers[a][i][3]+"px";b.style.top=2*
window.loadBuffers[a][i][4]+"px";b.style.left=2*window.loadBuffers[a][i][5]+"px";b.style.fontSize=2*window.loadBuffers[a][i][6]+"px";b.style.color=window.loadBuffers[a][i][7];var e=document.createTextNode(window.loadBuffers[a][i][0]);b.appendChild(e);el.id("contentDiv"+a).appendChild(b);customEvents.fireEvent(IOS_LOAD_VECTOR_END,{page:a,type:1})}}};this.getName=function(a){var b="000"+a;9<a&&(b="00"+a);99<a&&(b="0"+a);999<a&&(b=""+a);return b};var c=this,d=-1,n=-1;this.touch=function(){!c.block&&
!c.gesture&&!ZOOM_LOCK&&(d=Modernizr.touch?event.targetTouches[0].pageX:event.pageX)};this.endmove=function(){if(!c.block&&!c.gesture&&!ZOOM_LOCK&&(n=Modernizr.touch?event.changedTouches[0].pageX:event.pageX,-1!=d&&-1!=n)){var a=d-n;70<a?pageMediator.right():-70>a&&pageMediator.left();n=d=-1}};this.gesturestart=function(){c.gesture=!0;var a=c.currentPage;c.gestureDiv=el.id("divPage"+a);customEvents.fireEvent(ZOOM_ANIMATION_START);c.maxZoom=fbUtils.getMaxZoom(c.pageWidth,c.pageHeight);c.gestureDiv.style.top=
c.bookTop+"px";c.gestureDiv.style.left=c.bookLeft+"px";c.gestureDiv.id="exPage"+c.currentPage;HTML5lib.boxShadow(c.gestureDiv,"");HTML5lib.duration(c.gestureDiv,0);c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px)";el.id("mainFrame").appendChild(c.gestureDiv);if(el.id("videoDiv"+a))el.id("videoDiv"+a).style.opacity=0;c.destroyBook()};this.gesturechange=function(a){if(1<a.scale&&c.maxZoom>=a.scale)c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d("+a.scale+","+a.scale+
","+a.scale+")"};this.gestureend=function(a){var b=c.currentPage;setTimeout(function(){c.gesture=!1},150);var e=c.maxZoom>a.scale?a.scale:c.maxZoom,a=function(){var a=c.pageWidth;publicationData.page[b].wide&&(a/=2);a=a*e/(publicationData.page[b].width||publicationData.page.defaults.width);customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:a,page:b})};1.2>e?(setTimeout(function(){HTML5lib.duration(c.gestureDiv,200);c.gestureDiv.style.webkitTransform=
"translate3d(0px, 0px, 0px) scale3d(1.2,1.2,1.2)"},10),setTimeout(a,210),e=1.2):(c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d("+e+","+e+","+e+")",a())};this.goToZoom=function(a){if(!this.block&&!ZOOM_LOCK){customEvents.fireEvent(ZOOM_ANIMATION_START);if(el.id("videoDiv"+c))el.id("videoDiv"+c).style.opacity=0;var b=fbUtils.getMaxZoom(this.pageWidth,this.pageHeight),e=this,c=this.currentPage,g=publicationData.page[c].wide,d=el.id("divPage"+this.currentPage);d.style.top=this.bookTop+
"px";d.style.left=this.bookLeft+"px";d.style.webkitTransform="";d.id="exPage"+c;if(el.id("videoDiv"+c))el.id("videoDiv"+c).style.opacity=0;el.id("mainFrame").appendChild(d);a=1.5*window.innerWidth/this.pageWidth;a=a>b?b:a;setTimeout(function(){HTML5lib.duration(d,300);HTML5lib.changeOnlyScale(d,a,a,a)},10);var b=publicationData.page[c].width||publicationData.page.defaults.width,f=e.pageWidth;g&&(f/=2);var k=f*a/b;setTimeout(function(){e.destroyBook();customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,
{zoomFactor:k,page:c})},360)}}}
function TwoPagePublication(q){q=pageTable.getUserIDFromFileID(q||1);this.HORIZONTAL_MARGIN=this.VERTICAL_MARGIN=30;this.bookLeft=this.bookTop=this.bookHeight=this.bookWidth=this.pageHeight=this.pageWidth=0;this.pageBuff=3;this.currentPage={left:0,right:0};this.flipSpeed=1E3;this.loadBuffers={};this.active=this.gesture=this.block=!1;var c=this;this.doubleClick=0;this.currentPage.minus=function(){this.left-=2;this.right-=2};this.currentPage.plus=function(){this.left=1*this.left+2;this.right=1*this.right+
2};this.initSizes=function(){var a=2*publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>a?(this.bookHeight=window.innerHeight-2*this.VERTICAL_MARGIN,this.bookWidth=this.bookHeight*a,this.bookLeft=(window.innerWidth-this.bookWidth)/2,this.bookTop=this.VERTICAL_MARGIN):(this.bookWidth=window.innerWidth-2*this.HORIZONTAL_MARGIN,this.bookHeight=this.bookWidth/a,this.bookLeft=this.HORIZONTAL_MARGIN,this.bookTop=(window.innerHeight-this.bookHeight)/2);this.pageHeight=
this.bookHeight;this.pageWidth=this.bookWidth/2};this.init=function(){var a=this;customEvents.addListener(SHOW_SEARCH_RESULTS,function(){if(a.active)if(publicationData.rtlMode)for(var b=a.currentPage.right-a.pageBuff;b<=1*a.currentPage.left+a.pageBuff;b++)highlight.show(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b));else for(b=a.currentPage.left-a.pageBuff;b<=1*a.currentPage.right+a.pageBuff;b++)highlight.show(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b))});customEvents.addListener(CANCEL_SEARCH,
function(){if(a.active)if(publicationData.rtlMode)for(var b=a.currentPage.right-a.pageBuff;b<=1*a.currentPage.left+a.pageBuff;b++)highlight.hide(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b));else for(b=a.currentPage.left-a.pageBuff;b<=1*a.currentPage.right+a.pageBuff;b++)highlight.hide(pageTable.getFileIDFromUserID(b),el.id("highlightCanvas"+b))});customEvents.addListener(BOOK_FLIPPING_START,function(){a.block=!0});customEvents.addListener(BOOK_FLIPPING_END,function(){a.block=!1});
customEvents.addListener(IOS_LOAD_PAGE_START,function(a){if(2===a.data.type){var a=a.data.page,e=el.add("div");e.id="preloader"+a;e.style.position="absolute";e.style.left="50%";e.style.top="50%";e.style.width="10em";e.style.height="10em";e.style.margin="-3em 0 0 -5em";workspace.preloader.add(e);el.id("pageDiv"+a).appendChild(e)}});customEvents.addListener(IOS_LOAD_BITMAP_END,function(a){2===a.data.type&&el.del("preloader"+a.data.page)});customEvents.addListener(IOS_LOAD_VECTOR_END,function(){})};
this.drawBook=function(a){this.active=!0;a=a||-10;-10!=a&&this.pageConverter(a);this.initSizes();this.init();a=document.createElement("div");a.id="publicationDiv";a.style.webkitPerspective="3000";a.style.width=this.bookWidth+"px";a.style.height=this.bookHeight+"px";a.style.top=this.bookTop+"px";a.style.left=this.bookLeft+"px";a.style.textAlign="center";a.style.position="absolute";a.style.opacity="1";a.style.zIndex="1000";el.id("mainFrame").appendChild(a);if(publicationData.rtlMode)for(a=this.currentPage.right-
this.pageBuff;a<=1*this.currentPage.left+this.pageBuff;a++)this.drawPage(a);else for(a=this.currentPage.left-this.pageBuff;a<=1*this.currentPage.right+this.pageBuff;a++)this.drawPage(a);1==this.currentPage.right||1==this.currentPage.left?this.drawBookShadow("first"):this.currentPage.left==publicationData.pageUserCount&&!publicationData.rtlMode?this.drawBookShadow("last"):this.currentPage.right==publicationData.pageUserCount&&publicationData.rtlMode?this.drawBookShadow("last"):this.drawBookShadow("std")};
this.drawPage=function(a){if(0<a&&a<=publicationData.pageUserCount){var b=0!=a%2?a+"x"+(1*a+1):a-1+"x"+a;if(el.id(b))e=el.id(b);else{var e=el.add("div");e.id=b;e.style.width=this.pageWidth+"px";e.style.height=this.pageHeight+"px";e.style.position="absolute";e.style.webkitTransformStyle="preserve-3d";e.style.webkitTransition="-webkit-transform "+this.flipSpeed+"ms";if(publicationData.rtlMode)if(a>=this.currentPage.left)e.style.left=0,e.style.zIndex=publicationData.pageCount-a,e.style.webkitTransform=
"rotate3d(0, 1, 0, 0deg)",e.style.webkitTransformOrigin="100% 100%";else{if(a<=this.currentPage.right)e.style.left=this.pageWidth+"px",e.style.zIndex=a,e.style.webkitTransform="rotate3d(0, -1, 0, 0deg)",e.style.webkitTransformOrigin="0% 0%"}else if(a<=this.currentPage.left)e.style.left=0,e.style.zIndex=a,e.style.webkitTransform="rotate3d(0, 1, 0, 0deg)",e.style.webkitTransformOrigin="100% 100%";else if(a>=this.currentPage.right)e.style.left=this.pageWidth+"px",e.style.zIndex=publicationData.pageCount-
a,e.style.webkitTransform="rotate3d(0, -1, 0, 0deg)",e.style.webkitTransformOrigin="0% 0%"}b=el.add("div");b.id="pageDiv"+a;b.style.position="absolute";b.style.width=this.pageWidth+"px";b.style.height=this.pageHeight+"px";b.style.overflow="hidden";b.className="page";b.style.webkitBackfaceVisibility="hidden";b.style.backgroundColor=publicationData.page[pageTable.getFileIDFromUserID(a)].BGColor||publicationData.page.defaults.BGColor;if(publicationData.rtlMode)if(a>=this.currentPage.left&&0==a%2){b.style.zIndex=
"-1";var c=-1;b.style.webkitTransform="rotateY(180deg)"}else if(a>=this.currentPage.left&&0!=a%2)b.style.zIndex="1",c=1;else if(a<=this.currentPage.right&&0==a%2)b.style.zIndex="1",c=1;else{if(a<=this.currentPage.right&&0!=a%2)b.style.zIndex="-1",c=-1,b.style.webkitTransform="rotateY(180deg)"}else if(a<=this.currentPage.left&&0==a%2)b.style.zIndex="1",c=1;else if(a<=this.currentPage.left&&0!=a%2)b.style.zIndex="-1",b.style.webkitTransform="rotateY(180deg)",c=-1;else if(a>=this.currentPage.right&&
0==a%2)b.style.zIndex="-1",b.style.webkitTransform="rotateY(180deg)",c=-1;else if(a>=this.currentPage.right&&0!=a%2)b.style.zIndex="1",c=1;e.appendChild(b);this.drawPageContent(b,a,c);el.id("publicationDiv").appendChild(e);if(publicationData.page[pageTable.getFileIDFromUserID(a)].stub){var g=pageTable.getFileIDFromUserID(a);ZOOM_LOCK&&el.id("exPage"+g)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+g)},50))}else customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:a,
type:2})}};this.drawPageContent=function(a,b,e){var c=pageTable.getFileIDFromUserID(b),g=this.pageHeight,d=publicationData.page[c].wide?2*this.pageWidth:this.pageWidth,f=publicationData.page[c].width||publicationData.page.defaults.width,k=publicationData.page[c].height||publicationData.page.defaults.height,l=f/k;if(d/g>l)var h=g,m=h*l,d=(d-m)/2,g=0;else m=d,h=m/l,d=0,g=(g-h)/2;d=publicationData.rtlMode?0==b%2&&publicationData.page[c].wide?d-this.pageWidth:d:0!=b%2&&publicationData.page[c].wide?d-
this.pageWidth:d;l=el.add("canvas");l.id="substraitCanvas"+b;l.width=m;l.height=h;l.style.position="absolute";l.style.left=d+"px";l.style.top=g+"px";l.style.zIndex=e;l.style.webkitBackfaceVisibility="hidden";a.appendChild(l);var o=m/(2*f),p=publicationData.page[pageTable.getFileIDFromUserID(b)].format||publicationData.page.defaults.format;if("js+jpg"===p||"js+png"===p)p=el.add("div"),p.id="contentDiv"+b,p.style.width=2*f+"px",p.style.height=2*k+"px",p.style.position="absolute",p.style.left=d+"px",
p.style.top=g+"px",p.style.webkitTransformOrigin="0% 0%",p.style.webkitTransform="scale("+o+")",p.style.zIndex=e,a.appendChild(p);if(1!=b){f=el.add("canvas");f.id="shadow"+b;f.width=100;f.height=this.pageHeight;f.style.position="absolute";f.style.zIndex=e;if(0==b%2){if(0==b%2&&b!=publicationData.pageUserCount)publicationData.rtlMode?(f.style.left="0px",this.drawRightShadow(f)):(f.style.left=this.pageWidth-100+"px",this.drawLeftShadow(f))}else publicationData.rtlMode?(f.style.left=this.pageWidth-100+
"px",this.drawLeftShadow(f)):(f.style.left="0px",this.drawRightShadow(f));a.appendChild(f)}f=el.add("canvas");f.id="highlightCanvas"+b;f.width=m;f.height=h;f.style.position="absolute";f.style.left=d+"px";f.style.top=g+"px";f.style.zIndex=e;a.appendChild(f);highlight.show(pageTable.getFileIDFromUserID(b),f);new LinksLayer(f,pageTable.getFileIDFromUserID(b));if(publicationData.page[c].stub){customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:b,type:2});var n=pageTable.getFileIDFromUserID(b);ZOOM_LOCK&&
el.id("exPage"+n)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+n)},50),ZOOM_LOCK=!1)}else this.loadImage(l,c,b)};this.getName=function(a){var b="000"+a;9<a&&(b="00"+a);99<a&&(b="0"+a);999<a&&(b=""+a);return b};this.loadImage=function(a,b,e){var c=a.getContext("2d");c.fillStyle="rgb(255,255,255)";var g=publicationData.page[b].proportions||publicationData.page.defaults.proportions,d=publicationData.size.proportions,f=a.width,a=a.height,k=new Image,l=publicationData.page[b].format||
publicationData.page.defaults.format,h=publicationData.page[b].zoomFormat||publicationData.page.defaults.zoomFormat||publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===l){var m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".jpg";this.loadContent(e,f)}else"js+png"===l?(m=COMMON_FOLDER+"/page-substrates/page"+this.getName(b)+".png",this.loadContent(e,f)):"jpg"===h?m=ASSETS_FOLDER+"/pages/page"+this.getName(b)+"_i2.jpg":"png"===h&&(m=ASSETS_FOLDER+"/pages/page"+
this.getName(b)+"_i2.png");changeUrlWhenPubl(m,function(a){k.src=a});if(g>=d)var o=f,p=(o/g+0.5).toFixed(0),n=0,q=(a-p)/2;else p=a,o=(p*g+0.5).toFixed(0),n=(f-o)/2,q=0;k.onload=function(){ZOOM_LOCK&&el.id("exPage"+b)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+b)},50));fileID=null;c.drawImage(k,n,q,o,p);customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:e,type:2})}};this.loadContent=function(a){var a=pageTable.getFileIDFromUserID(a),a=ASSETS_FOLDER+"/pages/ios/page"+
this.getName(a)+".js",b=document.getElementsByTagName("head")[0],e=document.createElement("script");e.id="formPrinter";e.type="text/javascript";changeUrlWhenPubl(a,function(a){e.src=a});b.appendChild(e);window.fakeLoadComplete=function(a){window.loadBuffers[a]=window.loadBuffer;for(i in window.loadBuffers[a]){var b=el.add("p");b.style.position="absolute";b.style.fontFamily=window.loadBuffers[a][i][1];b.style.width=2*window.loadBuffers[a][i][2]+"px";b.style.height=2*window.loadBuffers[a][i][3]+"px";
b.style.top=2*window.loadBuffers[a][i][4]+"px";b.style.left=2*window.loadBuffers[a][i][5]+"px";b.style.fontSize=2*window.loadBuffers[a][i][6]+"px";b.style.color=window.loadBuffers[a][i][7];var e=document.createTextNode(window.loadBuffers[a][i][0]);b.appendChild(e);e=pageTable.getUserIDFromFileID(a);el.id("contentDiv"+e).appendChild(b)}}};this.destroyPage=function(a){el.del(a)};this.clearPage=function(a){el.id("substraitCanvas"+a)&&el.del("substraitCanvas"+a);el.id("contentDiv"+a)&&el.del("contentDiv"+
a);el.id("highlightCanvas"+a)&&el.del("highlightCanvas"+a)};this.goToPage=function(a){a=pageTable.getUserIDFromFileID(a);if(publicationData.rtlMode)if(a>=this.currentPage.right-2&&a<this.currentPage.right){var b=1*this.currentPage.right+3+"x"+(1*this.currentPage.left+3);el.id(b)&&this.destroyPage(b);this.shiftLeft();this.currentPage.minus();this.drawPage(1*this.currentPage.left-this.pageBuff);this.drawPage(1*this.currentPage.right-this.pageBuff)}else if(a<=1*this.currentPage.left+2&&a>this.currentPage.left)b=
1*this.currentPage.right-3+"x"+(1*this.currentPage.left-3),el.id(b)&&this.destroyPage(b),this.shiftRight(),this.currentPage.plus(),this.drawPage(1*this.currentPage.left+this.pageBuff),this.drawPage(1*this.currentPage.right+this.pageBuff);else{if(a!=this.currentPage.left&&a!=this.currentPage.right){a<this.currentPage.right?(this.clearPage(1*this.currentPage.right-1),this.clearPage(1*this.currentPage.right-2),this.shiftLeft()):(this.clearPage(1*this.currentPage.left+1),this.clearPage(1*this.currentPage.left+
2),this.shiftRight());this.pageConverter(a);var e=this;setTimeout(function(){e.destroyBook();e.drawBook(a)},this.flipSpeed)}}else a<=this.currentPage.right+2&&a>this.currentPage.right?(this.shiftLeft(),b=1*this.currentPage.left-3+"x"+(1*this.currentPage.right-3),this.currentPage.plus(),el.id(b)&&this.destroyPage(b),this.drawPage(1*this.currentPage.left+this.pageBuff),this.drawPage(1*this.currentPage.right+this.pageBuff)):a>=this.currentPage.left-2&&a<this.currentPage.left?(this.shiftRight(),b=1*this.currentPage.left+
3+"x"+(1*this.currentPage.right+3),this.currentPage.minus(),el.id(b)&&this.destroyPage(b),this.drawPage(1*this.currentPage.left-this.pageBuff),this.drawPage(1*this.currentPage.right-this.pageBuff)):a!=this.currentPage.left&&a!=this.currentPage.right&&(a>this.currentPage.right?(this.clearPage(1*this.currentPage.right+1),this.clearPage(1*this.currentPage.right+2),this.shiftLeft()):(this.clearPage(1*this.currentPage.left-1),this.clearPage(1*this.currentPage.left-2),this.shiftRight()),this.pageConverter(a),
e=this,setTimeout(function(){e.destroyBook();e.drawBook(a)},this.flipSpeed))};this.shiftLeft=function(){if(publicationData.rtlMode)var a=1*this.currentPage.right-1+"x"+this.currentPage.right,b=publicationData.pageCount-this.currentPage.right,e=89999+this.currentPage.right;else a=this.currentPage.right+"x"+(1*this.currentPage.right+1),b=this.currentPage.right,e=1E5-this.currentPage.right;var c=el.id(a);customEvents.fireEvent(BOOK_FLIPPING_START);c.style.webkitTransform="rotate3d(0, -1, 0, 0deg)"==
c.style.webkitTransform?"rotate3d(0, -1, 0, 179."+e+"deg)":"rotate3d(0, 1, 0, 0deg)";var d=this;setTimeout(function(){c.style.zIndex=b;for(var a=c.getElementsByTagName("*"),e=0;e<a.length;e++){var d=a[e].style.zIndex;a[e].style.zIndex=1==d?-1:100==d?-100:-100==d?100:1}},this.flipSpeed/3);var d=this,j=d.currentPage.right;publicationData.rtlMode?(2==j&&d.drawBookShadow("first"),d=this,a=function(){j==publicationData.pageUserCount&&d.drawBookShadow("std");if(0<d.currentPage.left&&d.currentPage.right<=
publicationData.pageUserCount)var a=[d.currentPage.left,d.currentPage.right];else 0>=d.currentPage.left?a=[d.currentPage.right]:d.currentPage.right>publicationData.pageUserCount&&(a=[d.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:a})}):(j==publicationData.pageUserCount-1&&d.drawBookShadow("last"),d=this,a=function(){1==j&&d.drawBookShadow("std");if(0<d.currentPage.left&&d.currentPage.right<=publicationData.pageUserCount)var a=[d.currentPage.left,d.currentPage.right];else 0>=d.currentPage.left?
a=[d.currentPage.right]:d.currentPage.right>publicationData.pageUserCount&&(a=[d.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:a})});setTimeout(a,this.flipSpeed)};this.shiftRight=function(){var a=this;if(publicationData.rtlMode)var b=this.currentPage.left+"x"+(1*this.currentPage.left+1),e=this.currentPage.left,c=1E5-this.currentPage.left;else b=1*this.currentPage.left-1+"x"+this.currentPage.left,e=publicationData.pageCount-this.currentPage.left,c=89999+this.currentPage.right;var d=
el.id(b);customEvents.fireEvent(BOOK_FLIPPING_START);d.style.webkitTransform="rotate3d(0, 1, 0, 0deg)"==d.style.webkitTransform?"rotate3d(0, 1, 0, 179."+c+"deg)":"rotate3d(0, -1, 0, 0deg)";a=this;setTimeout(function(){for(var a=d.getElementsByTagName("*"),b=0;b<a.length;b++){var c=a[b].style.zIndex;a[b].style.zIndex=1==c?-1:100==c?-100:-100==c?100:1}d.style.zIndex=e},this.flipSpeed/3);var j=a.currentPage.left;publicationData.rtlMode?(j==publicationData.pageUserCount-1&&a.drawBookShadow("last"),a=
this,b=function(){1==j&&a.drawBookShadow("std");if(0<a.currentPage.left&&a.currentPage.right<=publicationData.pageUserCount)var b=[a.currentPage.left,a.currentPage.right];else 0>=a.currentPage.left?b=[a.currentPage.right]:a.currentPage.right>publicationData.pageUserCount&&(b=[a.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:b})}):(2==j&&a.drawBookShadow("first"),a=this,b=function(){j==publicationData.pageUserCount&&a.drawBookShadow("std");if(0<a.currentPage.left&&a.currentPage.right<=
publicationData.pageUserCount)var b=[a.currentPage.left,a.currentPage.right];else 0>=a.currentPage.left?b=[a.currentPage.right]:a.currentPage.right>publicationData.pageUserCount&&(b=[a.currentPage.left]);customEvents.fireEvent(BOOK_FLIPPING_END,{page:b})});setTimeout(b,this.flipSpeed)};var d=-1,n=-1,c=this;this.touch=function(){!c.block&&!c.gesture&&!ZOOM_LOCK&&(d=Modernizr.touch?event.targetTouches[0].pageX:event.pageX)};this.endmove=function(){if(!c.block&&!c.gesture&&!ZOOM_LOCK&&(n=Modernizr.touch?
event.changedTouches[0].pageX:event.pageX,-1!=d&&-1!=n)){var a=d-n;70<a?pageMediator.right():-70>a&&pageMediator.left();n=d=-1}};this.gesturestart=function(a){c.gestureStartTrigg=!0;customEvents.fireEvent(ZOOM_ANIMATION_START);c.gesture=!0;var a=a.target.id.match(/\d+/i),b=pageTable.getFileIDFromUserID(a);publicationData.page[b].wide&&0!=a%2&&!publicationData.rtlMode&&(a-=1);publicationData.page[b].wide&&0===a%2&&publicationData.rtlMode&&(a=1*a+1);c.gestureDiv=el.id("pageDiv"+a);c.gesturePage=a;c.maxZoom=
!publicationData.page[b].wide?fbUtils.getMaxZoom(c.pageWidth,c.pageHeight):fbUtils.getMaxZoom(c.bookWidth,c.pageHeight);el.id("mainFrame").appendChild(c.gestureDiv);el.del("shadow"+a);c.gestureDiv.style.webkitTransform="";c.gestureDiv.style.zIndex=1E5;c.gestureDiv.id="exPage"+b;c.gestureDiv.style.top=c.bookTop+"px";c.gestureDiv.style.webkitTransformOrigin="50% 50%";if(publicationData.page[b].wide)c.gestureDiv.style.width=2*c.pageWidth+"px";if(publicationData.rtlMode&&0===a%2)c.gestureDiv.style.left=
c.bookLeft+c.pageWidth+"px";else if(!publicationData.rtlMode&&0===a%2)c.gestureDiv.style.left=c.bookLeft+"px";else if(!publicationData.rtlMode&&0!=a%2)c.gestureDiv.style.left=c.bookLeft+c.pageWidth+"px";else if(publicationData.rtlMode&&0!=a%2)c.gestureDiv.style.left=c.bookLeft+"px"};this.gesturechange=function(a){if(1<a.scale&&c.maxZoom>=a.scale)c.gestureDiv.style.webkitTransform="translate3d(0px, 0px, 0px) scale3d("+a.scale+","+a.scale+","+a.scale+")"};this.gestureend=function(a){if(c.gestureStartTrigg){c.gestureStartTrigg=
!1;var b=1.3;setTimeout(function(){c.gesture=!1},150);var e=pageTable.getFileIDFromUserID(c.gesturePage);pageMediator.changePage(e);var d=c.gesturePage,a=a.scale>c.maxZoom?c.maxZoom:a.scale;a<b&&(a=b);var g=c.pageWidth*a/(publicationData.page[e].width||publicationData.page.defaults.width);c.destroyBook();c.gestureDiv.style.webkitTransitionDuration="300ms";if(publicationData.rtlMode&&0===d%2)var j=-c.pageWidth/2;else!publicationData.rtlMode&&0===d%2?j=c.pageWidth/2:!publicationData.rtlMode&&0!=d%2?
j=-c.pageWidth/2:publicationData.rtlMode&&0!=d%2&&(j=c.pageWidth/2);publicationData.page[e].wide&&(j=0);(b=a)?(c.gestureDiv.style.webkitTransitionDuration="300ms",c.gestureDiv.style.webkitTransform="translate3d("+j+"px, 0px, 0px) scale3d("+a+","+a+","+a+")",setTimeout(function(){customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:g,page:e})},310)):(c.gestureDiv.style.webkitTransform="translate3d("+j+"px, 0px, 0px) scale3d("+a+","+a+","+a+")",customEvents.fireEvent(START_ZOOM_PRELOADER),
customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:g,page:e}))}};this.destroyBook=function(){el.del("publicationDiv");this.active=!1};this.pageConverter=function(a){publicationData.rtlMode?0!=a%2?(this.currentPage.left=a,this.currentPage.right=a-1):(this.currentPage.left=1*a+1,this.currentPage.right=a):0!=a%2?(this.currentPage.left=a-1,this.currentPage.right=a):(this.currentPage.left=a,this.currentPage.right=1*a+1);this.currentPage.left*=1;this.currentPage.right*=1};this.pageConverter(q);this.drawBookShadow=
function(a){var b=publicationData.pageUserCount+"x"+publicationData.pageUserCount,e=publicationData.pageUserCount-3+"x"+(publicationData.pageUserCount-2);"first"==a?(el.id("3x4")?HTML5lib.boxShadow(el.id("3x4"),"0px 0px 3px #000"):HTML5lib.boxShadow(el.id("1x2"),"0px 0px 3px #000"),HTML5lib.boxShadow(el.id("publicationDiv"),"0px 0px 0px #000")):"last"==a?(el.id(e)?HTML5lib.boxShadow(el.id(e),"0px 0px 3px #000"):HTML5lib.boxShadow(el.id(b),"0px 0px 3px #000"),HTML5lib.boxShadow(el.id("publicationDiv"),
"0px 0px 0px #000")):(HTML5lib.boxShadow(el.id("publicationDiv"),"0px 0px 3px #000"),el.id(e)?HTML5lib.boxShadow(el.id(e),"0px 0px 0px #000"):el.id(b)?HTML5lib.boxShadow(el.id(b),"0px 0px 0px #000"):el.id("pageDiv3")?HTML5lib.boxShadow(el.id("3x4"),"0px 0px 0px #000"):el.id("pageDiv1")&&HTML5lib.boxShadow(el.id("1x2"),"0px 0px 0px #000"))};this.goToZoom=function(a){if(!this.block&&!ZOOM_LOCK){var b=pageTable.getFileIDFromUserID(a);maxZoom=!publicationData.page[b].wide?fbUtils.getMaxZoom(this.pageWidth,
this.pageHeight):fbUtils.getMaxZoom(this.bookWidth,this.pageHeight);pageMediator.changePage(b);customEvents.fireEvent(ZOOM_ANIMATION_START);publicationData.page[b].wide&&0!=a%2&&!publicationData.rtlMode&&(a-=1);publicationData.page[b].wide&&0==a%2&&publicationData.rtlMode&&(a=1*a+1);var e=el.id("pageDiv"+a);el.id("mainFrame").appendChild(e);e.style.webkitTransform="";e.style.zIndex=99999;e.id="exPage"+b;e.style.top=this.bookTop+"px";if(publicationData.rtlMode&&0===a%2)e.style.left=this.bookLeft+this.pageWidth+
"px";else if(!publicationData.rtlMode&&0===a%2)e.style.left=this.bookLeft+"px";else if(!publicationData.rtlMode&&0!=a%2)e.style.left=this.bookLeft+this.pageWidth+"px";else if(publicationData.rtlMode&&0!=a%2)e.style.left=this.bookLeft+"px";el.del("shadow"+a);if(publicationData.page[b].wide)e.style.width=2*this.pageWidth+"px";var c=window.innerWidth/(publicationData.page[b].wide?this.bookWidth:this.pageWidth),c=c>maxZoom?maxZoom:c,d=this,j=function(){e.style.webkitTransitionDuration="300ms";e.style.webkitBackfaceVisibility=
"";if(!publicationData.page[b].wide)e.style.left=d.bookLeft+d.pageWidth/2+"px";e.style.webkitTransformOrigin="50% 50%";e.style.webkitTransform="translate3d(0px,0px,10px) scale3d("+c+","+c+","+c+")";j=null};setTimeout(j,10);var f=d.pageWidth*c/(publicationData.page[b].width||publicationData.page.defaults.width);setTimeout(function(){d.destroyBook();customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END,{zoomFactor:f,page:b})},350)}};this.drawLeftShadow=function(a){ctx=
a.getContext("2d");var b=ctx.createLinearGradient(0,0,100,0);b.addColorStop(0,"rgba(0,0,0,0)");b.addColorStop(0.6,"rgba(0,0,0,0.1)");b.addColorStop(0.95,"rgba(0,0,0,0.2)");b.addColorStop(1,"rgba(0,0,0,0.65)");ctx.fillStyle=b;ctx.fillRect(0,0,a.width,a.height)};this.drawRightShadow=function(a){ctx=a.getContext("2d");var b=ctx.createLinearGradient(this.bookWidth/20,0,0,0);b.addColorStop(0,"rgba(0,0,0,0.0)");b.addColorStop(0.4,"rgba(0,0,0,0.05)");b.addColorStop(0.8,"rgba(0,0,0,0.20)");b.addColorStop(1,
"rgba(0,0,0,0.15)");ctx.fillStyle=b;ctx.fillRect(0,0,a.width,a.height)}}
function ZoomIOSPublication(q){this.bookHeight=this.bookWidth=this.pageHeight=this.pageWidth=0;this.pageShift=20;this.active=!1;this.currentPage=q||1;this.pageBuff=0;this.flipSpeed=500;this.loadBuffers={};this.gesture=!1;this.zoomFactor=this.translateScrollY=this.translateScrollX=0;this.zoomIOSpeed=500;this.scrollbars=this.block=this.active=!1;this.scrolls={};this.init=function(){var a=this;customEvents.addListener(SHOW_SEARCH_RESULTS,function(){if(a.active){highlight.show(a.currentPage);for(var b=
a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.show(b)}});customEvents.addListener(CANCEL_SEARCH,function(){if(a.active){highlight.hide(a.currentPage);for(var b=a.currentPage-a.pageBuff;b<=1*a.currentPage+a.pageBuff;b++)b!==a.currentPage&&highlight.hide(b)}});customEvents.addListener(BOOK_FLIPPING_START,function(){a.block=!0});customEvents.addListener(BOOK_FLIPPING_END,function(){a.block=!1});customEvents.addListener(ROTATE_DEVICE,function(){a.active&&a.rotate()});
customEvents.addListener(IOS_LOAD_PAGE_START,function(a){if(3===a.data.type){var a=a.data.page,e=el.add("div");e.id="preloader"+a;e.style.position="absolute";e.style.left=window.innerWidth/2+"px";e.style.top=window.innerHeight/2+"px";e.style.width="10em";e.style.height="10em";e.style.margin="-3em 0 0 -5em";workspace.preloader.add(e);el.id("page"+a).appendChild(e)}});customEvents.addListener(IOS_LOAD_BITMAP_END,function(a){3===a.data.type&&el.del("preloader"+a.data.page)});customEvents.addListener(IOS_LOAD_VECTOR_END,
function(){})};this.initSizes=function(a,b){this.zoomFactor=a=a||this.zoomFactor;var b=b||this.currentPage,e=publicationData.size.width/publicationData.size.height;this.pageWidth=(publicationData.page[b].width||publicationData.page.defaults.width)*a;this.pageHeight=this.pageWidth/e;this.pageLeft=(window.innerWidth-this.pageWidth)/2;this.pageTop=(window.innerHeight-this.pageHeight)/2;this.widePageWidth=2*this.pageWidth;this.widePageLeft=(window.innerWidth-this.widePageWidth)/2};this.drawBook=function(a,
b){b=b||!1;this.active=!0;this.currentPage=a;this.init();var e=el.add("div");e.id="zoomBook";e.style.width="100%";e.style.height="100%";e.style.position="absolute";el.id("mainFrame").appendChild(e);for(e=this.currentPage-this.pageBuff;e<=1*this.currentPage+this.pageBuff;e++)0<e&&e<=publicationData.pageCount&&this.drawPage(e,b)};this.drawPage=function(a,b){var e=publicationData.page[a].wide,b=e?b||{x:this.widePageLeft,y:this.pageTop}:b||{x:this.pageLeft,y:this.pageTop},c=el.add("div");c.id="pageMask"+
a;c.style.position="absolute";c.style.width="100%";c.style.height="100%";c.style.webkitTransform="translate3d("+(publicationData.rtlMode?(this.currentPage-a)*window.innerWidth:(a-this.currentPage)*window.innerWidth)+"px,0px,0px)";var d=el.add("div");d.id="page"+a;d.style.position="absolute";d.style.overflow="hidden";d.style.width=e?this.widePageWidth+"px":this.pageWidth+"px";d.style.height=this.pageHeight+"px";HTML5lib.boxShadow(d,"0px 0px 3px #000");if("photo_album"!=publicationData.type&&"document"!=
publicationData.type)d.style.backgroundColor=publicationData.page[a].BGColor||publicationData.page.defaults.BGColor;if(0<this.pageTop)d.style.top=this.pageTop+"px";if(e){if(0<this.widePageLeft)d.style.left=this.widePageLeft+"px"}else if(0<this.pageLeft)d.style.left=this.pageLeft+"px";c.appendChild(d);el.id("zoomBook").appendChild(c);var j=this.injectCanvas(d,a),d=null;this.scrolls[a]=new iScroll("pageMask"+a,{hScrollbar:this.scrollbars,vScrollbar:this.scrollbars,zoom:!1});b.y=0==b.y?b.y-j:b.y;this.scrolls[a].scrollTo(b.x,
b.y,0);var f=this,k=e?this.widePageWidth:this.pageWidth;this.slideMode=k>window.innerWidth?!0:!1;var l=function(){if(f.slideMode)if(150<f.scrolls[a].x&&(1!=f.currentPage&&!publicationData.rtlMode||f.currentPage!=publicationData.pageCount&&publicationData.rtlMode))pageMediator.left(),Modernizr.touch?el.id("pageMask"+a).removeEventListener("touchmove",l):el.id("pageMask"+a).removeEventListener("mousemove",l),f.scrolls[a].destroy();else if(f.scrolls[a].x<window.innerWidth-k-150&&(f.currentPage!=publicationData.pageCount&&
!publicationData.rtlMode||1!=f.currentPage&&publicationData.rtlMode))pageMediator.right(),Modernizr.touch?el.id("pageMask"+a).removeEventListener("touchmove",l):el.id("pageMask"+a).removeEventListener("mousemove",l),f.scrolls[a].destroy()};Modernizr.touch?c.addEventListener("touchmove",l):c.addEventListener("mousemove",l);c=null};this.injectCanvas=function(a,b){var c=publicationData.page[b].wide,d=this.pageHeight,g=publicationData.page[b].width||publicationData.page.defaults.width,j=publicationData.page[b].height||
publicationData.page.defaults.height,f=g/j,k=c?this.widePageWidth:this.pageWidth;if((c?this.widePageWidth/d:this.pageWidth/d)>f)var c=d,l=c*f,f=(k-l)/2,d=0;else l=k,c=l/f,f=0,d=(d-c)/2;var d=d.toFixed(0),k=(c/3).toFixed(0),h=el.add("canvas");h.id="1substraitCanvas"+b;h.width=l;h.height=k;h.style.position="absolute";h.style.left=f+"px";h.style.top=d+"px";h.style.webkitTransform="translate3d(0,0,0)";a.appendChild(h);h=el.add("canvas");h.id="2substraitCanvas"+b;h.width=l;h.height=k;h.style.position=
"absolute";h.style.left=f+"px";h.style.top=1*d+1*k-0.1+"px";h.style.webkitTransform="translate3d(0,0,0)";a.appendChild(h);h=el.add("canvas");h.id="3substraitCanvas"+b;h.width=l;h.height=c-2*k;h.style.position="absolute";h.style.left=f+"px";h.style.top=1*d+2*k-1.1+"px";h.style.webkitTransform="translate3d(0,0,0)";a.appendChild(h);publicationData.page[b].stub?(customEvents.fireEvent(IOS_LOAD_BITMAP_END,{page:b,type:3}),ZOOM_LOCK&&el.id("exPage"+b)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+
b)},150))):(customEvents.fireEvent(IOS_LOAD_PAGE_START,{page:b,type:3}),this.loadImage(c,k,b));k=l/(2*g);h=publicationData.page[b].format||publicationData.page.defaults.format;if("js+jpg"===h||"js+png"===h)h=el.add("div"),h.id="zContentDiv"+b,h.style.width=2*g+"px",h.style.height=2*j+"px",h.style.position="absolute",h.style.left=f+"px",h.style.top=d+"px",h.style.webkitTransformOrigin="0% 0%",h.style.webkitTransform="scale("+k+")",a.appendChild(h);var m=el.add("canvas");m.id="highlightCanvas"+b;m.width=
l;m.height=c;m.style.position="absolute";m.style.left=f+"px";m.style.top=d+"px";m.style.opacity=0;a.appendChild(m);var o=function(){m.style.opacity=1;customEvents.removeListener(IOS_LOAD_BITMAP_END,o)};customEvents.addListener(IOS_LOAD_BITMAP_END,o);new LinksLayer(m,b);highlight.show(b,m);return d};this.loadImage=function(a,b,c){var d=el.id("1substraitCanvas"+c),g=d.getContext("2d");g.fillStyle="rgb(255,255,255)";var d=el.id("2substraitCanvas"+c),j=d.getContext("2d");j.fillStyle="rgb(255,255,255)";
var d=el.id("3substraitCanvas"+c),f=d.getContext("2d");f.fillStyle="rgb(255,255,255)";var k=publicationData.page[c].proportions||publicationData.page.defaults.proportions,l=publicationData.size.proportions,d=d.width,h=new Image,m=publicationData.page[c].format||publicationData.page.defaults.format,o=publicationData.page[c].zoomFormat||publicationData.page.defaults.zoomFormat||publicationData.page[c].format||publicationData.page.defaults.format;if("js+jpg"===m){var p=COMMON_FOLDER+"/page-substrates/page"+
this.getName(c)+".jpg";this.loadContent(c,d)}else"js+png"===m?(p=COMMON_FOLDER+"/page-substrates/page"+this.getName(c)+".png",this.loadContent(c,d)):"jpg"===o?p=ASSETS_FOLDER+"/pages/page"+this.getName(c)+"_i2.jpg":"png"===o&&(p=ASSETS_FOLDER+"/pages/page"+this.getName(c)+"_i2.png");changeUrlWhenPubl(p,function(a){h.src=a});if(k>=l)var n=d,k=(n/k).toFixed(0),q=0,k=(a-k)/2;else n=(a*k).toFixed(0),q=(d-n)/2,k=0;var r=k>b?b:k,s=k>2*b?2*b:r-b,r=k,s=r-b,t=r+s-b;h.onload=function(){customEvents.fireEvent(IOS_LOAD_BITMAP_END,
{page:c,type:3});g.drawImage(h,q,r,n,a);j.drawImage(h,q,s,n,a);f.drawImage(h,q,t,n,a);setTimeout(function(){ZOOM_LOCK&&el.id("exPage"+c)&&(customEvents.fireEvent(STOP_ZOOM_PRELOADER),setTimeout(function(){el.del("exPage"+c)},150))},300)}};this.loadContent=function(a){var a=ASSETS_FOLDER+"/pages/ios/page"+this.getName(a)+".js",b=document.getElementsByTagName("head")[0],c=document.createElement("script");c.id="formPrinter";c.type="text/javascript";changeUrlWhenPubl(a,function(a){c.src=a});b.appendChild(c);
window.fakeLoadComplete=function(a){window.loadBuffers[a]=window.loadBuffer;for(i in window.loadBuffers[a]){var b=el.add("p");b.style.position="absolute";b.style.fontFamily=window.loadBuffers[a][i][1];b.style.width=2*window.loadBuffers[a][i][2]+"px";b.style.height=2*window.loadBuffers[a][i][3]+"px";b.style.top=2*window.loadBuffers[a][i][4]+"px";b.style.left=2*window.loadBuffers[a][i][5]+"px";b.style.fontSize=2*window.loadBuffers[a][i][6]+"px";b.style.color=window.loadBuffers[a][i][7];var c=document.createTextNode(window.loadBuffers[a][i][0]);
b.appendChild(c);el.id("zContentDiv"+a).appendChild(b);customEvents.fireEvent(IOS_LOAD_VECTOR_END,{page:a,type:3})}}};this.rotate=function(){this.initSizes();0<this.pageLeft?el.id("page"+this.currentPage).style.left=publicationData.page[this.currentPage].wide?this.widePageLeft+"px":this.pageLeft+"px":el.id("page"+this.currentPage).style.left="0px";0<this.pageTop?el.id("page"+this.currentPage).style.top=this.pageTop+"px":el.id("page"+this.currentPage).style.top="0px"};this.slideLeft=function(a){var b=
el.id("pageMask"+this.currentPage),a=publicationData.rtlMode?el.id("pageMask"+a):el.id("pageMask"+a);b.style.webkitTransitionDuration="300ms";a.style.webkitTransitionDuration="300ms";b.style.webkitTransform="translate3d("+-window.innerWidth+"px,0px,0px)";a.style.webkitTransform="translate3d(0px,0px,0px)";var c=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:c.currentPage})},300)};this.slideRight=function(a){var b=el.id("pageMask"+this.currentPage),a=publicationData.rtlMode?
el.id("pageMask"+a):el.id("pageMask"+a);b.style.webkitTransitionDuration="300ms";a.style.webkitTransitionDuration="300ms";b.style.webkitTransform="translate3d("+window.innerWidth+"px,0px,0px)";a.style.webkitTransform="translate3d(0px,0px,0px)";var c=this;setTimeout(function(){customEvents.fireEvent(BOOK_FLIPPING_END,{page:c.currentPage})},300)};this.goToPage=function(a){if(this.currentPage<a){this.drawPage(a,{x:0,y:0});publicationData.rtlMode?this.slideRight(a):this.slideLeft(a);var b=this.currentPage;
this.currentPage=a;var c=this;setTimeout(function(){c.destroyPage(b)},300)}else if(this.currentPage>a)this.drawPage(a,{x:0,y:0}),publicationData.rtlMode?this.slideLeft(a):this.slideRight(a),b=this.currentPage,this.currentPage=a,c=this,setTimeout(function(){c.destroyPage(b)},300)};this.destroyPage=function(a){this.scrolls[a].destroy();delete this.scrolls[a];el.del("page"+a);el.del("pageMask"+a)};this.destroyBook=function(){el.del("zoomBook");this.active=!1};this.goToOnePage=function(){if(!ZOOM_LOCK){customEvents.fireEvent(ZOOM_ANIMATION_START);
if(el.id("videoDiv"+a))el.id("videoDiv"+a).style.opacity=0;var a=this.currentPage,b=publicationData.page[a].wide,c=this;this.scrolls[a].destroy();delete this.scrolls[a];var d=publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>d?oneBookHeight=window.innerHeight-20:(oneBookWidth=window.innerWidth-20,oneBookHeight=oneBookWidth/d);b&&(oneBookHeight/=2);var g=oneBookHeight/this.pageHeight,j=el.id("page"+a);j.style.webkitTransformOrigin="50% 50%";el.id("mainFrame").appendChild(j);
j.style.webkitTransform="";j.id="exPage"+a;j.style.zIndex="100000";j.style.webkitBoxShadow="";setTimeout(function(){j.style.webkitTransitionDuration="300ms";j.style.top=c.pageTop+"px";j.style.left=b?c.widePageLeft+"px":c.pageLeft+"px";HTML5lib.changeOnlyScale(j,g,g,g)},20);setTimeout(function(){c.destroyBook();customEvents.fireEvent(START_ZOOM_PRELOADER);customEvents.fireEvent(ZOOM_ANIMATION_END_TO_ONE,{page:a})},320)}};this.goToTwoPage=function(){if(!ZOOM_LOCK){customEvents.fireEvent(ZOOM_ANIMATION_START);
if(el.id("videoDiv"+a))el.id("videoDiv"+a).style.opacity=0;var a=this.currentPage,b=publicationData.page[a].wide,c=this,d=pageTable.getUserIDFromFileID(a);this.scrolls[a].destroy();this.scrolls[a]=null;var g=2*publicationData.size.width/publicationData.size.height;window.innerWidth/window.innerHeight>g?(twoBookHeight=window.innerHeight-60,twoBookWidth=twoBookHeight*g):(twoBookWidth=window.innerWidth-60,twoBookHeight=twoBookWidth/g);var j=0;publicationData.rtlMode&&0===d%2?j=twoBookWidth/4:publicationData.rtlMode&&
0!=d%2?j=-twoBookWidth/4:!publicationData.rtlMode&&0===d%2?j=-twoBookWidth/4:!publicationData.rtlMode&&0!=d%2&&(j=twoBookWidth/4);var f=twoBookHeight/this.pageHeight,k=el.id("page"+a);k.style.webkitTransformOrigin="50% 50%";el.id("mainFrame").appendChild(k);k.style.webkitTransform="";k.id="exPage"+a;k.style.zIndex="100000";k.style.webkitBoxShadow="";b&&(j=0);setTimeout(function(){k.style.webkitTransitionDuration="300ms";k.style.top=c.pageTop+"px";k.style.left=b?c.widePageLeft+"px":c.pageLeft+"px";
k.style.webkitTransform="translate3d("+j+"px,0,0) scale3d("+f+","+f+","+f+")";customEvents.fireEvent(START_ZOOM_PRELOADER,{shift:j})},20);setTimeout(function(){c.destroyBook();customEvents.fireEvent(ZOOM_ANIMATION_END_TO_TWO,{page:d})},320)}};this.getName=function(a){var b="000"+a;9<a&&(b="00"+a);99<a&&(b="0"+a);999<a&&(b=""+a);return b};var c=this;this.gesturestart=function(a){customEvents.fireEvent(ZOOM_ANIMATION_START);if(el.id("videoDiv"+page))el.id("videoDiv"+page).style.opacity=0;c.gesture=
!0;c.zoomPage=c.currentPage;c.x=c.scrolls[c.zoomPage].x;c.y=c.scrolls[c.zoomPage].y;c.scrolls[c.zoomPage].destroy();c.scrolls[c.zoomPage]=null;c.zoomDiv=el.id("page"+c.zoomPage);c.maxZoom=fbUtils.getMaxZoom(publicationData.page[c.zoomPage].wide?2*c.pageWidth:c.pageWidth,c.pageHeight);if(1===orientationObserver.getType()){var b=window.innerWidth/window.innerHeight,d=publicationData.size.width/publicationData.size.height;b>d?oneBookHeight=window.innerHeight-20:(oneBookWidth=window.innerWidth-20,oneBookHeight=
oneBookWidth/d);c.minZoom=oneBookHeight/c.pageHeight;if(publicationData.page[c.zoomPage].wide)c.minZoom=oneBookHeight/2/c.pageHeight}else b=window.innerWidth/window.innerHeight,d=2*publicationData.size.width/publicationData.size.height,b>d?(twoBookHeight=window.innerHeight-60,c.twoBookWidth=twoBookHeight*d):(c.twoBookWidth=window.innerWidth-60,twoBookHeight=c.twoBookWidth/d),c.minZoom=twoBookHeight/c.pageHeight;for(i in c.zoomDiv.getElementsByTagName("*"))c.zoomDiv.getElementsByTagName("*")[i].id=
"";el.id("mainFrame").appendChild(c.zoomDiv);c.zoomDiv.id="exPage"+c.zoomPage;c.zoomDiv.style.zIndex="100000";0>=c.pageTop?(c.zoomDiv.style.top=c.y+"px",b=(-c.y+a.pageY).toFixed(0)):b=(a.pageY-c.pageTop).toFixed(0);d=!publicationData.page[c.zoomPage].wide?c.pageLeft:c.widePageLeft;0>=d?(c.zoomDiv.style.left=c.x+"px",a=(-c.x+a.pageX).toFixed(0)):a=(a.pageX-d).toFixed(0);c.zoomDiv.style.webkitTransformOrigin=a+"px "+b+"px";c.destroyBook()};this.gesturechange=function(a){if(c.minZoom<=a.scale&&c.maxZoom>=
a.scale)c.zoomDiv.style.webkitTransform="scale3d("+a.scale+","+a.scale+","+a.scale+")"};this.gestureend=function(a){setTimeout(function(){c.gesture=!1},150);var b=a.scale>c.maxZoom?c.maxZoom:a.scale<c.minZoom?c.minZoom:a.scale;c.zoomDiv.style.webkitTransform="scale3d("+b+","+b+","+b+")";var d=c.pageHeight*b,n=publicationData.page[c.zoomPage].wide?2*c.pageWidth*b:c.pageWidth*b,a=publicationData.page[c.zoomPage].width||publicationData.page.defaults.width;publicationData.page[c.zoomPage].wide&&(a*=2);
var g=n/a,j=0>=c.zoomDiv.getBoundingClientRect().left?c.zoomDiv.getBoundingClientRect().left:0,f=0>=c.zoomDiv.getBoundingClientRect().top?c.zoomDiv.getBoundingClientRect().top:0,k=c.zoomDiv.getBoundingClientRect().top,l=window.innerHeight-c.zoomDiv.getBoundingClientRect().bottom,h=c.zoomDiv.getBoundingClientRect().left,m=window.innerWidth-c.zoomDiv.getBoundingClientRect().right,o=a=0;c.zoomDiv.style.webkitTransitionDuration="100ms";d<=window.innerHeight?o=(window.innerHeight-d)/2-k:d>window.innerHeight&&
0<k?o=-k:d>window.innerHeight&&0<l&&(o=l);n<=window.innerWidth?a=(window.innerWidth-n)/2-h:n>window.innerWidth&&0<m?a=0:n>window.innerWidth&&0<h&&(a=-h);var p={x:j,y:f},d=0;b<=c.minZoom&&2===orientationObserver.getType()?(n=pageTable.getUserIDFromFileID(c.zoomPage),!publicationData.rtlMode&&0===n%2?d=c.twoBookWidth/4:!publicationData.rtlMode&&0!=n%2?d=-c.twoBookWidth/4:publicationData.rtlMode&&0===n%2?d=-c.twoBookWidth/4:publicationData.rtlMode&&0!=n%2&&(d=c.twoBookWidth/4),publicationData.page[c.zoomPage].wide&&
(d=0),c.zoomDiv.style.webkitTransform="translate3d("+(a-d)+"px,"+o+"px,0px) scale3d("+b+","+b+","+b+")"):c.zoomDiv.style.webkitTransform="translate3d("+a+"px,"+o+"px,0px) scale3d("+b+","+b+","+b+")";c.zoomDiv.style.webkitBoxShadow="";customEvents.fireEvent(START_ZOOM_PRELOADER,{shift:-d});setTimeout(function(){b>c.minZoom?customEvents.fireEvent(ZOOM_ZOOM_ANIMATION_END,{zoomFactor:g,page:c.zoomPage,startPos:p}):1===orientationObserver.getType()?customEvents.fireEvent(ZOOM_ANIMATION_END_TO_ONE,{page:c.zoomPage}):
customEvents.fireEvent(ZOOM_ANIMATION_END_TO_TWO,{page:pageTable.getUserIDFromFileID(c.zoomPage)})},180)};var d=-1,n=-1,c=this;this.touch=function(){this.slideMode=(publicationData.page[c.currentPage].wide?this.widePageWidth:this.pageWidth)>window.innerWidth?!0:!1;!c.block&&!c.gesture&&!ZOOM_LOCK&&!c.slideMode&&(d=Modernizr.touch?event.targetTouches[0].pageX:event.pageX)};this.endmove=function(){this.slideMode=(publicationData.page[c.currentPage].wide?this.widePageWidth:this.pageWidth)>window.innerWidth?
!0:!1;if(!c.block&&!c.gesture&&!ZOOM_LOCK&&!c.slideMode&&(n=Modernizr.touch?event.changedTouches[0].pageX:event.pageX,-1!=d&&-1!=n)){var a=d-n;120<a?pageMediator.right():-120>a&&pageMediator.left();n=d=-1}}};
